---
title: "CnR Variability"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Variability/CnR_Variability.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the peaks

```{r peaks, message=FALSE}
library(rtracklayer)
library(EnrichedHeatmap)
library(GenomicFeatures)
library(EnsDb.Mmusculus.v79)

# Generate feature annotation
prom <- promoters(genes(EnsDb.Mmusculus.v79),
                  upstream = 1500, downstream = 500)
prom <- prom[seqnames(prom) %in% c(as.character(1:19), "X", "Y", "MT"),]
tss <- promoters(genes(EnsDb.Mmusculus.v79), 
                 upstream = 0, downstream = 1)
tss <- tss[seqnames(tss) %in% c(as.character(1:19), "X", "Y", "MT"),]

# H3K4me3 peaks
files <- list.files("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/CnR/Peaks/H3K4me3/BroadPeaks/", full.names = TRUE)

# Bedgraph files
bedgraph.files <- list.files("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/CnR/bedgraphs/H3K4me3/", full.names = TRUE)

# Read in genes that change in variability over pseudotime
```

# Cut and Run peaks for these genes that were detected in the variability analysis

```{r CnR}
cur_files <- list.files("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/CnR/bedgraphs/H3K4me3/", 
                        full.names = TRUE)

# H3K4me3 spermatids day 24
cur_file <- import(cur_files[12])

# Exclude blacklisted regions
cur_removed <- overlapsAny(cur_file, blacklist)
cur_file <- cur_file[!cur_removed]
cur_file <- cur_file[seqnames(cur_file) %in%
                         c(as.character(1:19), "X", "Y", "MT"),]
seqlevels(cur_file) <- c(as.character(1:19), "X", "Y", "MT")


# Loop through gene sets
for(i in unique(df.out$regulation)){
  cur_genes <- rownames(df.out)[df.out$regulation == i]
  cur_tss <- tss[tss@elementMetadata$gene_id %in% cur_genes]
  
  cur_mat = normalizeToMatrix(cur_file, cur_tss, 
                        value_column = "score",
                        extend = 5000, mean_mode = "w0", 
                        w = 50, keep = c(0,0.99))

  EnrichedHeatmap(cur_mat, col = c("white", "red", "black"))
}



mat.tss = normalizeToMatrix(cur_bed, tss.X, 
                        value_column = "score",
                        extend = 5000, mean_mode = "w0", 
                        w = 50, keep = c(0,0.99))
```





