---
title: "Global analysis of ChIP-Seq data"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Cnr/Global_analysis.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in libraries and data

```{r library}
library(csaw)
library(rtracklayer)
library(Rsamtools)
library(reshape)
library(ggplot2)
library(ggsci)

names <- c("H3K4me1_ChIPSeq_SC.sorted.bam", "H3K4me1_ChIPSeq_ST.sorted.bam",
           "H3K4me3_ChIPSeq_SC.sorted.bam", "H3K4me3_ChIPSeq_ST.sorted.bam",
           "H3K27ac_ChIPSeq_SC.sorted.bam", "H3K27ac_ChIPSeq_ST.sorted.bam",
           "H27me3_ChIPSeq_SC.sorted.bam", "H27me3_ChIPSeq_ST.sorted.bam",
           "Input_ChIPSeq_SC.sorted.bam", "Input_ChIPSeq_ST.sorted.bam")

files <- paste("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Data/Hammoud_CSC/ChipSeq/bam/", names, sep = "")

# Blacklisted regions
black <- import("http://mitra.stanford.edu/kundaje/akundaje/release/blacklists/mm10-mouse/mm10.blacklist.bed.gz")
seqlevels(black) <- sub("chr", "", seqlevels(black))
seqnames(black) <- sub("chr", "", seqnames(black))

# Parameter for reading in bam files
param <- readParam(dedup=TRUE, minq=10, discard=black, pe="none")
```

# Count reads per chromosome

```{r}
# Count reads per chromosome
header <- scanBamHeader(files[1])
sizes <- header$`../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Data/Hammoud_CSC/ChipSeq/bam/H3K4me1_ChIPSeq_SC.sorted.bam`$targets
sizes <- sizes[!grepl("JH|GL|MT", names(sizes))]

# Generate Chr ranges
chr.ranges <- GRanges(seqnames = names(sizes), 
                      ranges = IRanges(start = rep(1, length(sizes)),
                                       end = sizes))

# Count reads per chromosome
out <- regionCounts(files, regions = chr.ranges, param=param)

# Calculate RPKM
cur_data <- assays(out)$counts
rownames(cur_data) <- names(sizes)
rpm <- t(t(cur_data)/(colSums(cur_data)/1000000))
rpkm <- rpm/(sizes/1000)
colnames(rpkm) <- names

cur_data.melt <- melt(rpkm)
cur_data.melt$cell_type <- sapply(as.character(cur_data.melt$X2), 
                                  function(n){unlist(strsplit(n, "_"))[3]})
cur_data.melt$mark <- sapply(as.character(cur_data.melt$X2), 
                                  function(n){unlist(strsplit(n, "_"))[1]})
cur_data.melt$X1 <- as.factor(rep(c(as.character(1:19), "X", "Y"), nrow(cur_data.melt)/21))
levels(cur_data.melt$X1) <- c(as.character(1:19), "X", "Y")

all.signal <- ggplot(cur_data.melt) + geom_point(aes(X1, value, 
                                                    colour = mark,
                                                    shape = cell_type), size = 2, position = position_dodge(width = 0.5)) + 
  scale_color_aaas(name = "Mark") + 
  ylab("RPKM") + xlab("")

ggsave(filename = "../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/Chip-Seq/global_signal_ChIP-Seq.pdf", 
       all.signal, width = 12, height = 5)
```