---
title: "Juveline differential expression analysis"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/DE/Juvenile_DE.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script berforms differential expression and GO term enrichment analysis 
between juveline animals and adult animals.

## Load data and libraries

```{r}
# Libraries
library(scran)
library(scater)
library(openxlsx)
library(DropletUtils)
library(goseq)
library(GO.db)
library(org.Mm.eg.db)
source("../../Functions/auxiliary.R")

# Read in data
sce.all <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all_clusters.rds")

# Read in length of genes
genelength <- read.table("../../Data/Genelength.txt", header = TRUE, sep = "\t")
```

# Perfom differential expression testing and GO enrichment 

## P10 vs adult

```{r}
# Combine data for testing
cur_sce <- sce.all[,grepl("P10", colData(sce.all)$Sample) | 
                     grepl("B6", colData(sce.all)$Sample)]
cur_sce <- cur_sce[Matrix::rowSums(logcounts(cur_sce)) > 0,]
cur_sce <- normalize(cur_sce)

# Read in empty droplets
sce.B6.1.empty <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/EmptyDrops/sce_do17815_empty.rds")
sce.B6.2.empty <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/EmptyDrops/sce_do17816_empty.rds")
sce.P10.empty <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/EmptyDrops/sce_do17821_empty.rds")

# Perform DE between ambient profiles
sce.ambient <- cbind(sce.B6.1.empty, sce.B6.2.empty, sce.P10.empty)
rm(sce.P10.empty)
sce.ambient <- sce.ambient[Matrix::rowSums(counts(sce.ambient)) > 0,]

cur_test <- DE.ambient(sce.ambient = sce.ambient, 
                       sample.names = c("B6","P10"), lfc = 2)

# Remove the genes that are DE
cur_sce <- cur_sce[rowData(cur_sce)$ID %in% rownames(cur_test)[cur_test$FDR > 0.1],]

logcounts(cur_sce) <- NULL

# Renomrmalize data
clusters <- quickCluster(cur_sce, method = "igraph", irlba.args = c("work" = 100))
cur_sce <- computeSumFactors(cur_sce, clusters=clusters)
cur_sce <- normalize(cur_sce, return_log = TRUE)

# Perform differential expression analysis for cell groups detected in P10
results.DE <- list()
results.GO <- list()

# Use same approach for ambient comparison 
sce.test <- cur_sce[,colData(cur_sce)$AnnotatedClusters == "Spermatogonia"]
sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
sce.test <- normalize(sce.test)
  
cur_markers <- findMarkers(sce.test,
                           clusters = ifelse(grepl("B6", colData(sce.test)$Sample),                                                      "Adults","P10"))
  
markers.P10 <- cur_markers$P10[cur_markers$P10$FDR < 0.1 & 
                                 cur_markers$P10$logFC.Adults > 0.4,]
markers.P10$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.P10),
                                                      rowData(cur_sce)$ID)]
markers.adult <- cur_markers$P10[cur_markers$Adults$FDR < 0.1 & 
                                 cur_markers$Adults$logFC.P10 > 0.4,]
markers.adult$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.adult),
                                                        rowData(cur_sce)$ID)]

results.DE[[paste("Group_Spermatogonia_P10", sep = "")]] <- markers.P10
results.DE[[paste("Group_Spermatogonia_Adult", sep = "")]] <- markers.adult
  
# GO analysis
# P10 genes
cur_genes <- as.integer(cur_markers$P10$FDR < 0.1 & 
                                  cur_markers$P10$logFC.Adults > 0.4)
names(cur_genes) <- rownames(cur_markers$P10)
  
pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
GO.wall=goseq(pwf,"mm10","ensGene")
enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]

# Add genenames to the GO categories
all_genes <- vector(length = nrow(enriched.GO))
for(j in 1:nrow(enriched.GO)){
  allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
  genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
  genes = as.character(genes[genes %in% markers.P10$Genename])
  all_genes[j] <- paste(genes, collapse = ", ")
}
enriched.GO$Genes <- all_genes
  
results.GO[[paste("Group_Spermatogonia_P10", sep = "")]] <- enriched.GO
  
# Adult genes
cur_genes <- as.integer(cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P10 > 0.4)
names(cur_genes) <- rownames(cur_markers$P10)
  
pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
GO.wall=goseq(pwf,"mm10","ensGene")
enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]

# Add genenames to the GO categories
all_genes <- vector(length = nrow(enriched.GO))
for(j in 1:nrow(enriched.GO)){
  allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
  genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
  genes = as.character(genes[genes %in% markers.adult$Genename])
  all_genes[j] <- paste(genes, collapse = ", ")
}
enriched.GO$Genes <- all_genes

results.GO[[paste("Group_Spermatogonia_Adult", sep = "")]] <- enriched.GO

# Write out table
write.xlsx(results.DE, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P10_adult_singleGenes.xlsx")

write.xlsx(results.GO, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P10_adult_GO.xlsx")
```

## P15 vs adult

```{r}
# Combine data for testing
cur_sce <- sce.all[,grepl("P15", colData(sce.all)$Sample) | 
                     grepl("B6", colData(sce.all)$Sample)]
cur_sce <- cur_sce[Matrix::rowSums(logcounts(cur_sce)) > 0,]
cur_sce <- normalize(cur_sce)

# Read in empty droplets
sce.P15.empty <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/EmptyDrops/sce_do17828_empty.rds")

# Perform DE between ambient profiles
sce.ambient <- cbind(sce.B6.1.empty, sce.B6.2.empty, sce.P15.empty)
rm(sce.P15.empty)
sce.ambient <- sce.ambient[Matrix::rowSums(counts(sce.ambient)) > 0,]

cur_test <- DE.ambient(sce.ambient = sce.ambient, 
                       sample.names = c("B6","P15"), lfc = 2)

# Remove the genes that are DE
cur_sce <- cur_sce[rowData(cur_sce)$ID %in% rownames(cur_test)[cur_test$FDR > 0.1],]

logcounts(cur_sce) <- NULL

# Renomrmalize data
clusters <- quickCluster(cur_sce, method = "igraph", irlba.args = c("work" = 100))
cur_sce <- computeSumFactors(cur_sce, clusters=clusters)
cur_sce <- normalize(cur_sce, return_log = TRUE)

# Perform differential expression analysis for cell groups detected in P15
results.DE <- list()
results.GO <- list()
cur_groups <- c("Early_Spermatocytes_1", "Early_Spermatocytes_2", 
                "Mid_Spermatocytes_1", "Mid_Spermatocytes_2", 
                "Late_Spermatocytes_1", "Late_Spermatocytes_2")

for(i in cur_groups){
  sce.test <- cur_sce[,colData(cur_sce)$AnnotatedClusters == i]
  sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
  sce.test <- normalize(sce.test)
  
  cur_markers <- findMarkers(sce.test,
                             clusters = ifelse(grepl("B6", colData(sce.test)$Sample), 
                                                     "Adults","P15"))
  
  markers.P15 <- cur_markers$P15[cur_markers$P15$FDR < 0.1 & 
                                   cur_markers$P15$logFC.Adults > 0.4,]
  markers.P15$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.P15),
                                                                 rowData(cur_sce)$ID)]
  markers.adult <- cur_markers$P15[cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P15 > 0.4,]
  markers.adult$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.adult),
                                                                 rowData(cur_sce)$ID)]
  results.DE[[paste("Group_", i, "_P15", sep = "")]] <- markers.P15
  results.DE[[paste("Group_", i, "_Adult", sep = "")]] <- markers.adult
  
  # GO analysis
  # P15 genes
  cur_genes <- as.integer(cur_markers$P15$FDR < 0.1 & 
                                   cur_markers$P15$logFC.Adults > 0.4)
  names(cur_genes) <- rownames(cur_markers$P15)
  
  if(sum(cur_genes) > 5){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
        genes = as.character(genes[genes %in% markers.P15$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  else {
   enriched.GO <- NULL 
  }
  
  results.GO[[paste("Group_", i, "_P15", sep = "")]] <- enriched.GO
  
  # Adult genes
  cur_genes <- as.integer(cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P15 > 0.4)
  names(cur_genes) <- rownames(cur_markers$P15)
  
  if(sum(cur_genes) > 5){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
        genes = as.character(genes[genes %in% markers.adult$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  
  results.GO[[paste("Group_", i, "_Adult", sep = "")]] <- enriched.GO
}

# Write out table
write.xlsx(results.DE, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P15_adult_singleGenes.xlsx")

write.xlsx(results.GO, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P15_adult_GO.xlsx")

```

## P20 vs adult

```{r}
# Combine data for testing
cur_sce <- sce.all[,grepl("P20", colData(sce.all)$Sample) | 
                     grepl("B6", colData(sce.all)$Sample)]
cur_sce <- cur_sce[Matrix::rowSums(logcounts(cur_sce)) > 0,]
cur_sce <- normalize(cur_sce)

# Read in empty droplets
sce.P20.empty <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/EmptyDrops/sce_do17824_empty.rds")

# Perform DE between ambient profiles
sce.ambient <- cbind(sce.B6.1.empty, sce.B6.2.empty, sce.P20.empty)
rm(sce.P20.empty)
sce.ambient <- sce.ambient[Matrix::rowSums(counts(sce.ambient)) > 0,]

cur_test <- DE.ambient(sce.ambient = sce.ambient, 
                       sample.names = c("B6","P20"), lfc = 2)

# Remove the genes that are DE
cur_sce <- cur_sce[rowData(cur_sce)$ID %in% rownames(cur_test)[cur_test$FDR > 0.1],]

logcounts(cur_sce) <- NULL

# Renomrmalize data
clusters <- quickCluster(cur_sce, method = "igraph", irlba.args = c("work" = 100))
cur_sce <- computeSumFactors(cur_sce, clusters=clusters)
cur_sce <- normalize(cur_sce, return_log = TRUE)

# Perform differential expression analysis for cell groups detected in P20
results.DE <- list()
results.GO <- list()
cur_groups <- c("Early_Spermatocytes_1", "Early_Spermatocytes_2", 
                "Mid_Spermatocytes_1", "Mid_Spermatocytes_2", 
                "Late_Spermatocytes_1", "Late_Spermatocytes_2", 
                "Meiosis")

for(i in cur_groups){
  sce.test <- cur_sce[,colData(cur_sce)$AnnotatedClusters == i]
  sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
  sce.test <- normalize(sce.test)
  
  cur_markers <- findMarkers(sce.test,
                             clusters = ifelse(grepl("B6", colData(sce.test)$Sample), 
                                                     "Adults","P20"))
  
  markers.P20 <- cur_markers$P20[cur_markers$P20$FDR < 0.1 & 
                                   cur_markers$P20$logFC.Adults > 0.4,]
  markers.P20$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.P20),
                                                                 rowData(cur_sce)$ID)]
  markers.adult <- cur_markers$P20[cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P20 > 0.4,]
  markers.adult$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.adult),
                                                                 rowData(cur_sce)$ID)]
  results.DE[[paste("Group_", i, "_P20", sep = "")]] <- markers.P20
  results.DE[[paste("Group_", i, "_Adult", sep = "")]] <- markers.adult
  
  # GO analysis
  # P20 genes
  cur_genes <- as.integer(cur_markers$P20$FDR < 0.1 & 
                                   cur_markers$P20$logFC.Adults > 0.4)
  names(cur_genes) <- rownames(cur_markers$P20)
  
  if(sum(cur_genes) > 5){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
        genes = as.character(genes[genes %in% markers.P20$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  else {
   enriched.GO <- NULL 
  }
  
  results.GO[[paste("Group_", i, "_P20", sep = "")]] <- enriched.GO
  
  # Adult genes
  cur_genes <- as.integer(cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P20 > 0.4)
  names(cur_genes) <- rownames(cur_markers$P20)
  
  if(sum(cur_genes) > 5){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
        genes = as.character(genes[genes %in% markers.adult$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  
  results.GO[[paste("Group_", i, "_Adult", sep = "")]] <- enriched.GO
}

# Write out table
write.xlsx(results.DE, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P20_adult_singleGenes.xlsx")

write.xlsx(results.GO, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P20_adult_GO.xlsx")

# Now exclude genes that are detected as DE across more than 50% of groups 
# these could hint at batch effects

genes.P20 <- rownames(results.DE[[1]])

for(i in seq(3, length(results.DE), 2)){
  genes.P20 <- intersect(genes.P20, rownames(results.DE[[i]]))
}

genes.adult <- rownames(results.DE[[2]])

for(i in seq(4, length(results.DE), 2)){
  genes.adult <- intersect(genes.adult, rownames(results.DE[[i]]))
}

# Exclude these genes from analysis
results.DE.new <- list()
results.GO.new <- list()

for(i in 1:length(results.DE)){
  cur_markers <- results.DE[[i]]
  cur_markers <- cur_markers[!(rownames(cur_markers) %in% genes.P20),]
  
  results.DE.new[[names(results.DE)[i]]] <- cur_markers
  
  # GO analysis
  # P20 genes
  cur_genes <- as.integer(cur_markers$P20$FDR < 0.1 & 
                                   cur_markers$P20$logFC.Adults > 0)
  names(cur_genes) <- rownames(cur_markers$P20)
  
  if(sum(cur_genes) > 10){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unlist(mget(allegs,org.Mm.egSYMBOL))
        genes = as.character(genes[genes %in% markers.P20$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  else {
   enriched.GO <- NULL 
  }
  
  results.GO[[paste("Group_", i, "_P20", sep = "")]] <- enriched.GO
  
  # Adult genes
  cur_genes <- as.integer(cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P20 > 0)
  names(cur_genes) <- rownames(cur_markers$P20)
  
  if(sum(cur_genes) > 10){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unlist(mget(allegs,org.Mm.egSYMBOL))
        genes = as.character(genes[genes %in% markers.adult$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  
  results.GO[[paste("Group_", i, "_Adult", sep = "")]] <- enriched.GO
}

# Write out table
write.xlsx(results.DE, "/Users/eling01/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/Direct_comparison/P20_adult_singleGenes.xlsx")

write.xlsx(results.GO, "/Users/eling01/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/Direct_comparison/P20_adult_GO.xlsx")
```

## P25 vs adult

## P30 vs adult

```{r}
# Combine data for testing
cur_sce <- sce.all[,grepl("P30", colData(sce.all)$Sample) | 
                     grepl("B6", colData(sce.all)$Sample)]
cur_sce <- cur_sce[Matrix::rowSums(logcounts(cur_sce)) > 0,]
cur_sce <- normalize(cur_sce)

# Read in empty droplets
sce.P30.empty <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/EmptyDrops/sce_do17825_empty.rds")

# Perform DE between ambient profiles
sce.ambient <- cbind(sce.B6.1.empty, sce.B6.2.empty, sce.P30.empty)
rm(sce.P30.empty)
sce.ambient <- sce.ambient[Matrix::rowSums(counts(sce.ambient)) > 0,]

cur_test <- DE.ambient(sce.ambient = sce.ambient, 
                       sample.names = c("B6","P30"), lfc = 2)

# Remove the genes that are DE
cur_sce <- cur_sce[rowData(cur_sce)$ID %in% rownames(cur_test)[cur_test$FDR > 0.1],]

logcounts(cur_sce) <- NULL

# Renomrmalize data
clusters <- quickCluster(cur_sce, method = "igraph", irlba.args = c("work" = 100))
cur_sce <- computeSumFactors(cur_sce, clusters=clusters)
cur_sce <- normalize(cur_sce, return_log = TRUE)

# Perform differential expression analysis for cell groups detected in P30
results.DE <- list()
results.GO <- list()
cur_groups <- c("Early_Spermatocytes_1", "Early_Spermatocytes_2", 
                "Mid_Spermatocytes_1", "Mid_Spermatocytes_2", 
                "Late_Spermatocytes_1", "Late_Spermatocytes_2", 
                "Meiosis", "S1", "S2", "S3", "S4", "S5", "S6", "S7",
                "S8", "S9", "S10", "S11", "S12", "S13", "S14")

for(i in cur_groups){
  sce.test <- cur_sce[,colData(cur_sce)$AnnotatedClusters == i]
  sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
  sce.test <- normalize(sce.test)
  
  cur_markers <- findMarkers(sce.test,
                             clusters = ifelse(grepl("B6", colData(sce.test)$Sample), 
                                                     "Adults","P30"))
  
  markers.P30 <- cur_markers$P30[cur_markers$P30$FDR < 0.1 & 
                                   cur_markers$P30$logFC.Adults > 0.4,]
  markers.P30$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.P30),
                                                                 rowData(cur_sce)$ID)]
  markers.adult <- cur_markers$P30[cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P30 > 0.4,]
  markers.adult$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.adult),
                                                                 rowData(cur_sce)$ID)]
  results.DE[[paste("Group_", i, "_P30", sep = "")]] <- markers.P30
  results.DE[[paste("Group_", i, "_Adult", sep = "")]] <- markers.adult
  
  # GO analysis
  # P30 genes
  cur_genes <- as.integer(cur_markers$P30$FDR < 0.1 & 
                                   cur_markers$P30$logFC.Adults > 0.4)
  names(cur_genes) <- rownames(cur_markers$P30)
  
  if(sum(cur_genes) > 5){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
        genes = as.character(genes[genes %in% markers.P30$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  else {
   enriched.GO <- NULL 
  }
  
  results.GO[[paste("Group_", i, "_P30", sep = "")]] <- enriched.GO
  
  # Adult genes
  cur_genes <- as.integer(cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P30 > 0.4)
  names(cur_genes) <- rownames(cur_markers$P30)
  
  if(sum(cur_genes) > 5){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
        genes = as.character(genes[genes %in% markers.adult$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  
  results.GO[[paste("Group_", i, "_Adult", sep = "")]] <- enriched.GO
}

# Write out table
write.xlsx(results.DE, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P30_adult_singleGenes.xlsx")

write.xlsx(results.GO, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P30_adult_GO.xlsx")
```

## P35 vs adult

```{r}
# Combine data for testing
cur_sce <- sce.all[,grepl("P35", colData(sce.all)$Sample) | 
                     grepl("B6", colData(sce.all)$Sample)]
cur_sce <- cur_sce[Matrix::rowSums(logcounts(cur_sce)) > 0,]
cur_sce <- normalize(cur_sce)

# Read in empty droplets
sce.P35.empty <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/EmptyDrops/sce_do17827_empty.rds")

# Perform DE between ambient profiles
sce.ambient <- cbind(sce.B6.1.empty, sce.B6.2.empty, sce.P35.empty)
rm(sce.P35.empty)
sce.ambient <- sce.ambient[Matrix::rowSums(counts(sce.ambient)) > 0,]

cur_test <- DE.ambient(sce.ambient = sce.ambient, 
                       sample.names = c("B6","P35"), lfc = 2)

# Remove the genes that are DE
cur_sce <- cur_sce[rowData(cur_sce)$ID %in% rownames(cur_test)[cur_test$FDR > 0.1],]

logcounts(cur_sce) <- NULL

# Renomrmalize data
clusters <- quickCluster(cur_sce, method = "igraph", irlba.args = c("work" = 100))
cur_sce <- computeSumFactors(cur_sce, clusters=clusters)
cur_sce <- normalize(cur_sce, return_log = TRUE)

# Perform differential expression analysis for cell groups detected in P35
results.DE <- list()
results.GO <- list()
cur_groups <- c("Early_Spermatocytes_1", "Early_Spermatocytes_2", 
                "Mid_Spermatocytes_1", "Mid_Spermatocytes_2", 
                "Late_Spermatocytes_1", "Late_Spermatocytes_2", 
                "Meiosis", "S1", "S2", "S3", "S4", "S5", "S6", "S7",
                "S8", "S9", "S10", "S11", "S12", "S13", "S14")

for(i in cur_groups){
  sce.test <- cur_sce[,colData(cur_sce)$AnnotatedClusters == i]
  sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
  sce.test <- normalize(sce.test)
  
  cur_markers <- findMarkers(sce.test,
                             clusters = ifelse(grepl("B6", colData(sce.test)$Sample), 
                                                     "Adults","P35"))
  
  markers.P35 <- cur_markers$P35[cur_markers$P35$FDR < 0.1 & 
                                   cur_markers$P35$logFC.Adults > 0.4,]
  markers.P35$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.P35),
                                                                 rowData(cur_sce)$ID)]
  markers.adult <- cur_markers$P35[cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P35 > 0.4,]
  markers.adult$Genename <- rowData(cur_sce)$Symbol[match(rownames(markers.adult),
                                                                 rowData(cur_sce)$ID)]
  results.DE[[paste("Group_", i, "_P35", sep = "")]] <- markers.P35
  results.DE[[paste("Group_", i, "_Adult", sep = "")]] <- markers.adult
  
  # GO analysis
  # P35 genes
  cur_genes <- as.integer(cur_markers$P35$FDR < 0.1 & 
                                   cur_markers$P35$logFC.Adults > 0.4)
  names(cur_genes) <- rownames(cur_markers$P35)
  
  if(sum(cur_genes) > 5){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
        genes = as.character(genes[genes %in% markers.P35$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  else {
   enriched.GO <- NULL 
  }
  
  results.GO[[paste("Group_", i, "_P35", sep = "")]] <- enriched.GO
  
  # Adult genes
  cur_genes <- as.integer(cur_markers$Adults$FDR < 0.1 & 
                                   cur_markers$Adults$logFC.P35 > 0.4)
  names(cur_genes) <- rownames(cur_markers$P35)
  
  if(sum(cur_genes) > 5){
    pwf=nullp(cur_genes,"mm10","ensGene", bias.data = genelength[names(cur_genes),])
    GO.wall=goseq(pwf,"mm10","ensGene")
    enriched.GO=GO.wall[p.adjust(GO.wall$over_represented_pvalue,method="fdr")<.1,]
  
  # Add genenames to the GO categories
    if(nrow(enriched.GO) > 0){
      all_genes <- vector(length = nrow(enriched.GO))
      for(j in 1:nrow(enriched.GO)){
        allegs = get(enriched.GO$category[j], org.Mm.egGO2ALLEGS)
        genes = unique(unlist(mget(allegs,org.Mm.egSYMBOL)))
        genes = as.character(genes[genes %in% markers.adult$Genename])
        all_genes[j] <- paste(genes, collapse = ", ")
      }
      enriched.GO$Genes <- all_genes
    }
  }
  
  results.GO[[paste("Group_", i, "_Adult", sep = "")]] <- enriched.GO
}

# Write out table
write.xlsx(results.DE, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P35_adult_singleGenes.xlsx")

write.xlsx(results.GO, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Juvenile_Adult_comparison/P35_adult_GO.xlsx")
```