---
title: "Marker genes"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in data

```{r data, message=FALSE}
library(scater)
library(scran)
library(openxlsx)
source("../../Functions/auxiliary.R")

# All cells
sce.all <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all_clusters.rds")

# B6 cells
sce.B6 <- sce.all[,grepl("B6", colData(sce.all)$Sample)]
sce.B6 <- sce.B6[,!(as.character(colData(sce.B6)$AnnotatedClusters) %in% 
c("PTM 1", "PTM 2", "tMg", "ECM", "Outliers"))]
sce.B6 <- normalize(sce.B6)

# P10 cells
sce.P10 <- sce.all[,grepl("P10", colData(sce.all)$Sample)]
sce.P10 <- sce.P10[,!(as.character(colData(sce.P10)$AnnotatedClusters) %in% "Early Spermatocytes 1")]
sce.P10 <- normalize(sce.P10)
```

# Spermatogenesis marker genes

```{r spermatogenesis}
sperm.markers <- marker.detection(sce.B6, as.character(colData(sce.B6)$AnnotatedClusters))

# Save rds
saveRDS(sperm.markers, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Marker_genes_B6.rds")

# Save xlsx
write.xlsx(sperm.markers, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Marker_genes_B6.xlsx")
```

# Somatic cells marker genes

```{r spermatogenesis}
somatic.markers <- marker.detection(sce.P10, as.character(colData(sce.P10)$AnnotatedClusters))

# Save rds
saveRDS(somatic.markers, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Marker_genes_P10.rds")

# Save xlsx
write.xlsx(somatic.markers, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Marker_genes_P10.xlsx")
```
