---
title: "Cell types in 10X data"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/CellTypeIdentification/CellTypesB6.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data preparation

To discover all cell-types in the 10X data, we will use the sorted C1 data as refernce

```{r load, message=FALSE}
# Load libraries and data
library(Matrix)
library(openxlsx)
library(RColorBrewer)
library(viridis)
source("../../Functions/auxiliary.R")

# Wild type 10X data
sce <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all_unfiltered.rds")
sce.B6 <- sce[,grepl("B6", colData(sce)$Sample)]
sce.B6 <- sce.B6[Matrix::rowMeans(counts(sce.B6)) > 0.1,]
sce.B6 <- normalize(sce.B6)
```

# Broad cluster detection

Detect braod clusters during differentiation in 10X wildtype cells.

```{r}
# Compute highly variable genes - auxiliary functions
HVG.genes <- HVG(sce.B6)

# Cluster data - auxiliary functions
ct <- DTC(sce.B6, HVG.genes)

# Recalculate tsne
set.seed(123)
sce.B6 <- scater::runTSNE(sce.B6)

ggplot(data.frame(tSNE1 = reducedDims(sce.B6)$TSNE[,1],
                  tSNE2 = reducedDims(sce.B6)$TSNE[,2],
                  sample = as.factor(ct))) +
  geom_point(aes(tSNE1, tSNE2, colour = sample))

# Find marker genes for each cluster
markers <- marker.detection(sce.B6, ct)

write.xlsx(markers, file = "../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/BroadGroups_B6.xlsx")

colData(sce.B6)$broad_clusters <- ct
```

# Subpopulation detection

```{r}
# Split sce into subgroups
all.sce <- split.sce(sce.B6, groups = unique(ct), colData.name = "broad_clusters")

# Calculate HVG
all.HVG.genes <- HVG(all.sce)

# Cluster each group
all.ct <- DTC(all.sce, all.HVG.genes, deepSplit = 1)

# Visualize all groups
clusters <- unlist(all.ct)
names(clusters) <- sapply(names(clusters), function(n){unlist(strsplit(n, "\\."))[2]})

# Broad clusters
ggplot(data.frame(tSNE1 = reducedDims(sce.B6)$TSNE[,1],
                  tSNE2 = reducedDims(sce.B6)$TSNE[,2],
                  sample = as.factor(colData(sce.B6)$broad_clusters))) +
  geom_point(aes(tSNE1, tSNE2, colour = sample))

# Subclusters
ggplot(data.frame(tSNE1 = reducedDims(sce.B6)$TSNE[,1],
                  tSNE2 = reducedDims(sce.B6)$TSNE[,2],
                  sample = as.factor(clusters[colData(sce.B6)$Barcode]))) +
  geom_point(aes(tSNE1, tSNE2, colour = sample)) + 
  scale_color_manual(values = c(brewer.pal(8, name = "Set1"), brewer.pal(8, name = "Set2"),
                                brewer.pal(8, name = "Set3")))


# Visualize marker genes
ggplot(data.frame(tsne1 = reducedDims(sce.B6)$TSNE[,1],
                  tsne2 = reducedDims(sce.B6)$TSNE[,2],
                  gene = logcounts(sce.B6)[rowData(sce.B6)$ID[rowData(sce.B6)$Symbol == "Stra8"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_color_viridis()

# Defb19 
ggplot(data.frame(tsne1 = reducedDims(sce.B6)$TSNE[,1],
                  tsne2 = reducedDims(sce.B6)$TSNE[,2],
                  gene = logcounts(sce.B6)[rowData(sce.B6)$ID[rowData(sce.B6)$Symbol == "Defb19"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_color_viridis()

# Prm1 
ggplot(data.frame(tsne1 = reducedDims(sce.B6)$TSNE[,1],
                  tsne2 = reducedDims(sce.B6)$TSNE[,2],
                  gene = logcounts(sce.B6)[rowData(sce.B6)$ID[rowData(sce.B6)$Symbol == "Prm1"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_color_viridis()

# Dazl 
ggplot(data.frame(tsne1 = reducedDims(sce.B6)$TSNE[,1],
                  tsne2 = reducedDims(sce.B6)$TSNE[,2],
                  gene = logcounts(sce.B6)[rowData(sce.B6)$ID[rowData(sce.B6)$Symbol == "Dazl"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_color_viridis()
```

I will find marker genes specific for each sub-population
in comparison to all other populations.

```{r}
# First save a data.frame containing all cluster labels
df <- data.frame(row.names = colData(sce.B6)$Barcode,
                 sample = colData(sce.B6)$Sample,
                 broad_clusters = colData(sce.B6)$broad_clusters)
df$sub_populations[df$broad_clusters == 1] <- clusters_1
df$sub_populations[df$broad_clusters == 2] <- clusters_2
df$sub_populations[df$broad_clusters == 3] <- clusters_3
df$sub_populations[df$broad_clusters == 4] <- clusters_4
df$sub_populations[df$broad_clusters == 5] <- clusters_5
df$sub_populations[df$broad_clusters == 6] <- clusters_6


# Now I order the groups by pseudotime
groupNames <- paste(df$broad_clusters, df$sub_populations, sep = "_")
df$OrderByPT[groupNames == "1_4"] <- 1
df$OrderByPT[groupNames == "1_6"] <- 2
df$OrderByPT[groupNames == "1_5"] <- 3
df$OrderByPT[groupNames == "1_3"] <- 4
df$OrderByPT[groupNames == "1_2"] <- 5
df$OrderByPT[groupNames == "1_1"] <- 6
df$OrderByPT[groupNames == "6_3"] <- 7
df$OrderByPT[groupNames == "6_2"] <- 8
df$OrderByPT[groupNames == "6_1"] <- 9
df$OrderByPT[groupNames == "6_4"] <- "Outliers"
df$OrderByPT[groupNames == "3_4"] <- 10
df$OrderByPT[groupNames == "3_1"] <- 11
df$OrderByPT[groupNames == "3_3"] <- 12
df$OrderByPT[groupNames == "3_2"] <- 13
df$OrderByPT[groupNames == "5_1"] <- 14
df$OrderByPT[groupNames == "5_3"] <- 15
df$OrderByPT[groupNames == "5_2"] <- 16
df$OrderByPT[groupNames == "5_4"] <- "Outliers"
df$OrderByPT[groupNames == "2_4"] <- 17
df$OrderByPT[groupNames == "2_3"] <- 18
df$OrderByPT[groupNames == "2_2"] <- 19
df$OrderByPT[groupNames == "2_1"] <- 20
df$OrderByPT[groupNames == "4_1"] <- 21
df$OrderByPT[groupNames == "4_2"] <- 22
df$OrderByPT[groupNames == "4_3"] <- 23

# visaulize all sub-clusters
library(RColorBrewer)

col_vector <- c(brewer.pal(12, "Set3")[4:12],brewer.pal(8, "Set2"), brewer.pal(9, "Set1") )

ggplot(data.frame(tSNE1 = reducedDims(sce.B6)$TSNE[,1],
                  tSNE2 = reducedDims(sce.B6)$TSNE[,2],
                  group = factor(df$OrderByPT, levels = c(1:23, "Outliers")))) +
  geom_point(aes(tSNE1, tSNE2, colour = group)) + 
  scale_color_manual(values = col_vector) + theme_minimal()

# Find colors 
library(ggsci)
col_vector <- c(pal_material(palette = c("brown"),n = 10, reverse = FALSE)(10)[5],
                pal_material(palette = c("green"),n = 10, reverse = FALSE)(10)[5],
                pal_material(palette = c("pink"),n = 4, reverse = FALSE)(4),
                pal_material(palette = c("purple"),n = 4, reverse = TRUE)(4),
                pal_material(palette = c("blue"),n = 4, reverse = FALSE)(4),
                pal_material(palette = c("deep-purple"),n = 4, reverse = TRUE)(4),
                pal_material(palette = c("indigo"),n = 5, reverse = FALSE)(5),
                pal_material(palette = c("blue-grey"),n = 10, reverse = FALSE)(10)[10])


# Find marker genes - remove outliers first
df.red <- df[!(df$OrderByPT == "Outliers"),]
B6.red <- sce.B6[,!(df$OrderByPT == "Outliers")]
B6.red <- normalize(B6.red)
markers <- findMarkers(B6.red, as.factor(df.red$OrderByPT))

rownames(rowData(B6.red)) <- rowData(B6.red)$ID

markers.spec <- lapply(markers, function(n){
  cur_n <- n[n$FDR < 0.1 & n[[3]] > 0 & n[[4]] > 0 &  n[[5]] > 0 & n[[6]] > 0 & n[[7]] > 0 & n[[8]] > 0 &
             n[[9]] > 0 & n[[10]] > 0 & n[[11]] > 0 & n[[12]] > 0 & n[[13]] > 0 & n[[14]] > 0 & 
             n[[15]] > 0 & n[[16]] > 0 & n[[17]] > 0 & n[[18]] > 0 & n[[19]] > 0 & n[[20]] > 0 &
             n[[21]] > 0 & n[[22]] > 0  & n[[23]] > 0  & n[[24]] > 0,]
  cur_n.1 <- cbind(as.data.frame(rowData(B6.red)$Symbol[match(rownames(cur_n), rowData(B6.red)$ID)]),cur_n)
  rownames(cur_n.1) <- rownames(cur_n)
  cur_n.1
})

markers.spec <- markers.spec[order(as.numeric(names(markers)))]

saveRDS(markers.spec, "../10X/Results/Marker_genes/All_markers.rds")

# Write out marker genes
openxlsx::write.xlsx(markers.spec, file = "Results/Marker_genes/SubGroups.xlsx")

# Save cluster IDs
colData(sce)$Cluster <- NA
colData(sce)$Cluster[grepl("B6", colData(sce)$Sample)] <- df$OrderByPT
```

```{r}
saveRDS(sce, "../data/10X_data/SCE_all.rds")
```