---
title: "Cell type enrichment"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/CellTypeIdentification/Enrichment') })

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in data and libraries

```{r libraries, message=FALSE}
library(scater)
library(randomForest)
library(RColorBrewer)
source("../../Functions/auxiliary.R")

# B6 data
sce <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all.rds")
sce.B6 <- sce[,grepl("B6", colData(sce)$Sample)]
sce.B6 <- normalize(sce.B6)

# Juvenile data
sce.juvenile <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_juvenile.rds")

# P20 
P20.sce <- sce.juvenile[,grepl("P20", colData(sce.juvenile)$Sample)]
P20.sce <- normalize(P20.sce)

set.seed(1234)
P20.sce <- runTSNE(P20.sce)

# Classifier for random forest learning
Tree.broad <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/Tree_broad_B6.rds")

Tree.sub <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/Tree_sub_B6.rds")
```

# Learn broad and sub-groups of P20 sample

```{r prediction}
# Prediction - broad groups
cur_genes <- rownames(logcounts(P20.sce))[rownames(logcounts(P20.sce)) %in% Tree.broad$Genes]
newdata <- matrix(data = 0, nrow = length(Tree.broad$Genes), ncol = ncol(P20.sce))
rownames(newdata) <- Tree.broad$Genes
newdata[cur_genes,] <- as.matrix(logcounts(P20.sce)[cur_genes,])
pred.P20.broad <- predict(object = Tree.broad, newdata = t(newdata))

ggplot(data.frame(tsne1 = reducedDims(P20.sce)$TSNE[,1],
                  tsne2 = reducedDims(P20.sce)$TSNE[,2],
                  sample = as.factor(pred.P20.broad))) +
  geom_point(aes(tsne1, tsne2, colour = sample)) 

# Prediction - sub groups
cur_genes <- rownames(logcounts(P20.sce))[rownames(logcounts(P20.sce)) %in% Tree.sub$Genes]
newdata <- matrix(data = 0, nrow = length(Tree.sub$Genes), ncol = ncol(P20.sce))
rownames(newdata) <- Tree.sub$Genes
newdata[cur_genes,] <- as.matrix(logcounts(P20.sce)[cur_genes,])
pred.P20.sub <- predict(object = Tree.sub, newdata = t(newdata))

ggplot(data.frame(tsne1 = reducedDims(P20.sce)$TSNE[,1],
                  tsne2 = reducedDims(P20.sce)$TSNE[,2],
                  sample = as.factor(pred.P20.sub))) +
  geom_point(aes(tsne1, tsne2, colour = sample)) 
```

# Define outlying cells

```{r outliers}
# HVG 
HVG.P20 <- HVG(P20.sce)

# Compute PCA
pca.P20 <- prcomp(t(logcounts(P20.sce)[HVG.P20,]))

# Density clustering to lable outlying cells
dbs <- dbscan(pca.P20$x[,1:3], eps = 4)

ggplot(data.frame(PC1 = pca.P20$x[,1],
                  PC2 = pca.P20$x[,2],
                  sample = as.factor(pred.P20.sub))) +
  geom_point(aes(PC1, PC2, colour = sample)) 

ggplot(data.frame(PC1 = pca.P20$x[,1],
                  PC2 = pca.P20$x[,2],
                  sample = as.factor(dbs$cluster))) +
  geom_point(aes(PC1, PC2, colour = sample)) 

# Assign outliers
pred.P20.broad[!(dbs$cluster %in% c(1,2,3,5))] <- "Outliers"
pred.P20.sub[!(dbs$cluster %in% c(1,2,3,5))] <- "Outliers"

ggplot(data.frame(PC1 = pca.P20$x[,1],
                  PC2 = pca.P20$x[,2],
                  sample = as.factor(pred.P20.sub))) +
  geom_point(aes(PC1, PC2, colour = sample))

colData(P20.sce)$BroadCluster <- pred.P20.broad
colData(P20.sce)$SubCluster <- pred.P20.sub
```

# Subcluster P20 cells to refine cell types

```{r clustersing}
# Split sce object
all.sce <- split.sce(P20.sce, groups = as.character(c(3, 4, 5, 6, 7)), 
                     colData.name = "SubCluster")

# HVG
# Calculate HVG
all.HVG.genes <- HVG(all.sce)

# Cluster each group
all.ct <- DTC(all.sce, all.HVG.genes, deepSplit = 0)

clusters <- unlist(all.ct)
names(clusters) <- sapply(names(clusters), function(n){unlist(strsplit(n, "\\."))[2]})

# Order based on pseudotime
col_vector <- c(brewer.pal(8, "Set1"), brewer.pal(8, "Set2"), brewer.pal(12, "Set3"))
names(col_vector) <- unique(clusters)
PT.P20 <- PT(rd = pca.P20$x[match(names(clusters), colData(P20.sce)$Barcode),1:3], 
             clusters = clusters,
            col_vector = col_vector)

plot(PT.P20[,"rank"], PT.P20[,"PC1"], col = col_vector[clusters])

# Compute median rank for each cluster
pos.PT <- vector(length = length(unique(clusters)))
names(pos.PT) <- unique(clusters)

for(i in 1:length(unique(clusters))){
  pos.PT[i] <- median(PT.P20[clusters == names(pos.PT)[i], "rank"], na.rm = TRUE)
}

pos.PT[order(pos.PT)]
pos.PT <- pos.PT[!is.na(pos.PT)]

# Refine clustering 
new.clusters <- as.character(colData(P20.sce)$SubCluster)
names(new.clusters) <- colData(P20.sce)$Barcode
new.clusters[names(clusters)] <- clusters

# Rename clusters based on their location on pseudotime
new.names <- paste(sapply(names(pos.PT)[order(pos.PT)], function(n){unlist(strsplit(n, "_"))[1]}),
                   c(seq(1, sum(sapply(names(pos.PT)[order(pos.PT)],
                                          function(n){unlist(strsplit(n, "_"))[1]}) == "3"), 1),
                     seq(1, sum(sapply(names(pos.PT)[order(pos.PT)],
                                          function(n){unlist(strsplit(n, "_"))[1]}) == "4"), 1),
                     seq(1, sum(sapply(names(pos.PT)[order(pos.PT)],
                                          function(n){unlist(strsplit(n, "_"))[1]}) == "5"), 1),
                     seq(1, sum(sapply(names(pos.PT)[order(pos.PT)],
                                          function(n){unlist(strsplit(n, "_"))[1]}) == "6"), 1),
                     seq(1, sum(sapply(names(pos.PT)[order(pos.PT)],
                                          function(n){unlist(strsplit(n, "_"))[1]}) == "7"), 1)),
                   sep = "_")

colData(P20.sce)$SubSubCluster <- new.clusters

ggplot(data.frame(PC1 = pca.P20$x[,1],
                  PC2 = pca.P20$x[,2],
                  sample = colData(P20.sce)$SubSubCluster)) +
  geom_point(aes(PC1, PC2, colour = sample))
```