---
title: "Figure S7"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_S7.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries

```{r data, message=FALSE}
library(scater)
library(plyr)
library(reshape2)
library(pheatmap)
library(viridis)

library(ggsci)
library(cowplot)
library(openxlsx)
source("../../Functions/auxiliary.R")
```


```{r}
# Read in sce data
sce <- readRDS("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all.rds")
sce <- sce[,grepl("Tc0|Tc1", colData(sce)$Sample) & 
             colData(sce)$AnnotatedClusters %in% levels(colData(sce)$AnnotatedClusters)[1:23]]
sce <- normalize(sce)

# Read in gene annotations
genenames <- read.table("../Data/Mouse_genes.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE)
rownames(genenames) <- genenames$Gene.stable.ID
```

# Differential expression analysis

The differential expression analysis is performed in the Tc0-Tc1_DE.Rmd script.
Here, we will only visualize the outcome.

```{r}
results.DE <- list()
p.list <- list()
cur_groups <- c("Spermatocytes_1", "Spermatocytes_2", 
                "Spermatocytes_3", "Spermatocytes_4", 
                "Spermatocytes_5", "Spermatocytes_6", "Spermatocytes_7", 
                "Meiosis", "S1", "S2", "S3", "S4", "S5", "S6", "S7",
                "S8", "S9", "S10", "S11", "S12", "S13", "S14")

for(i in cur_groups){
  sce.test <- sce[,colData(sce)$AnnotatedClusters == i]
  sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
  sce.test <- normalize(sce.test)
  
  # Sum counts with each batch and group
  mat <- matrix(data = NA, ncol = length(unique(colData(sce.test)$Library)), 
                nrow = nrow(counts(sce.test)))
  rownames(mat) <- rownames(counts(sce.test))
  colnames(mat) <- unique(paste(colData(sce.test)$Sample, 
                                colData(sce.test)$Library, sep = "_"))
  
  for(j in colnames(mat)){
    cur_batch <- unlist(strsplit(j, "_"))[2]
    mat[,j] <- Matrix::rowSums(counts(sce.test)[,colData(sce.test)$Library == cur_batch]) 
  }
  
  # Perform differential testing
  y <- DGEList(counts=mat,
               group=sapply(colnames(mat), 
                            function(n){unlist(strsplit(n, "_"))[1]}))
  y <- calcNormFactors(y)
  design <- model.matrix(~0+sapply(colnames(mat), function(n){unlist(strsplit(n, "_"))[1]}))
  colnames(design) <- c("Tc0", "Tc1")
  y <- estimateDisp(y,design)
  
  fit <- glmQLFit(y,design, robust = TRUE)
  qlf <- glmTreat(fit,coef=2, lfc = 0.5, 
                  contrast = makeContrasts(Tc1 - Tc0, levels = design))
  cur_markers <- topTags(qlf, n = nrow(qlf$table))$table
  
  cur_p <- ggplot(data.frame(cur_markers[cur_markers$FDR < 0.1,],
                              Tc1_Tc0 = factor(ifelse(grepl("ENSG",
                              rownames(cur_markers[cur_markers$FDR < 0.1,])), 
                                                      "Chr21",
                                                      "Mouse"), 
                                               levels = c("Chr21", "Mouse")))) + 
    geom_point(aes(logCPM, logFC, colour = Tc1_Tc0), size = 3) + 
    ylim(c(-22, 22)) + xlim(c(0, 8)) + geom_hline(yintercept = 0.5, lty = 2) + 
    geom_hline(yintercept = -0.5, lty = 2) +
    scale_colour_manual(values = c("Chr21" = "coral4", 
                                   "Mouse" = "steelblue")) +
    guides(colour = FALSE) + ggtitle(i)
  p.list[[i]] <- cur_p
  
}
```

# Save final figure

```{r}
final <- plot_grid(p.list[[1]], p.list[[2]], p.list[[3]], p.list[[4]],
                   p.list[[5]], p.list[[6]], p.list[[7]], p.list[[8]],
                   p.list[[9]], p.list[[10]], p.list[[11]], p.list[[12]],
                   p.list[[13]], p.list[[14]], p.list[[15]], p.list[[16]],
                   p.list[[17]], p.list[[18]], p.list[[19]], p.list[[20]],
                   p.list[[21]], p.list[[22]], ncol = 4, nrow = 6)

ggsave("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_S5/Fig_S5.pdf", final,
       height = 18, width = 15)
```
