---
title: "Figure S3"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_S3/Fig_S3.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script is for visualization of all juvenile samples across the adult trajectory. 

# Load data

```{r data, message=FALSE}
library(scran)
library(scater)
library(Matrix)
library(ggplot2)
library(Rtsne)
library(RColorBrewer)
library(irlba)
library(cowplot)
library(randomForest)
library(pheatmap)
library(viridis)
source("../../Functions/auxiliary.R")

# Bulk data
bulk <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/bulk/norm/1st_wave_bulk_norm_reverse-stranded.rds")

# Meta info for bulk data
meta <- read.table("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Tables/BulkSamples_stats.txt", sep = "\t")
```

```{r juvenile-samples}
# Visualize the different juvenile samples and adult cells
sce.all <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all.rds")
sce.all <- sce.all[, !(grepl("Tc", colData(sce.all)$Sample)) & 
                     colData(sce.all)$AnnotatedClusters != "Outliers"]

plot.list <- list()
for(i in paste("P", c(5, 10, 15, 20, 25, 30, 35), sep = "")){
  select <- grepl(paste(i, "|B6", sep = ""), colData(sce.all)$Sample)
  cur_df <- data.frame(tsne1 = reducedDims(sce.all)$TSNE[select,1],
                     tsne2 = reducedDims(sce.all)$TSNE[select,2],
                     clusters = ifelse(grepl("B6", colData(sce.all)$Sample[select]),
                                       "B6",
                       as.character(colData(sce.all)$AnnotatedClusters)[select])) 
  
  plot.list[[i]] <- ggplot(cur_df) +
  geom_point(aes(tsne1, tsne2, colour = clusters), size = 0.5) + scale_color_manual(values = c(metadata(sce.all)$color_vector, "B6" = "light grey")) + 
  ylab("tSNE 2") + xlab("tSNE 1") +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_blank(), axis.ticks = element_blank(),
          axis.title = element_text(size = 12, face = "bold")) + 
    guides(colour = FALSE)
}


# tSNE with all samples
cluster <- ggplot(data = data.frame(tSNE1 = reducedDims(sce.all)$TSNE[,1],
                         tSNE2 = reducedDims(sce.all)$TSNE[,2],
                         group = colData(sce.all)$AnnotatedClusters)) +
    geom_point(aes(tSNE1, tSNE2, colour = group), size = 0.5) +
    scale_color_manual(values = metadata(sce.all)$color_vector) + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_blank(), axis.ticks = element_blank(),
          axis.title = element_text(size = 12, face = "bold"), 
          line = element_blank()) + ggtitle("Cluster")

```

# Save final figure

```{r final}
legendA <- get_legend(cluster + theme(legend.position = "right"))
A <- plot_grid(plot.list[[1]], plot.list[[2]], plot.list[[3]], 
                   plot.list[[4]], plot.list[[5]], plot.list[[6]], plot.list[[7]], legendA, ncol = 4, nrow = 2)
ggsave(filename = "../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Supplemental_figures/Fig_S3/Fig_S3.pdf", 
       A, width = 15, height = 10)
```

# Map bulk libraries to stages

We perform a random forrest regression approach between the cluster labels 
and the top 50 marker genes for each group. The training is performed on adult B6 samples

```{r bulk mapping}
# Load marker genes
marker.genes <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Marker_genes_B6.rds")
cur_markers <- as.character(unlist(lapply(marker.genes, function(n){rownames(n)[1:50]})))
cur_markers <- cur_markers[cur_markers %in% rownames(bulk)]

# Train the classifier on adult B6 - remove outliers, unannotated cells and endothelia cells
sce.B6 <- sce.all[,grepl("B6", colData(sce.all)$Sample) & 
                    !(colData(sce.all)$AnnotatedClusters %in% 
             c("Outliers", "Endothelial_cells"))]
sce.B6 <- normalize(sce.B6)
labels <- factor(colData(sce.B6)$AnnotatedClusters,
                    levels = levels(colData(sce.B6)$AnnotatedClusters)[
                      levels(colData(sce.B6)$AnnotatedClusters) %in%
                        unique(colData(sce.B6)$AnnotatedClusters)])

# Create training and testing datasets
set.seed(1234)
sam <- sample(1:ncol(sce.B6), 2000)

train.data <- as.matrix(logcounts(sce.B6)[cur_markers,sam])
train.labels <- labels[sam] 
test.data <- as.matrix(logcounts(sce.B6)[cur_markers,-sam])
test.labels <- labels[-sam] 

# Scale the counts prior to training
# Z score
train.data.Z <- t(apply(train.data, 1, function(n){(n - mean(n))/sd(n)}))
test.data.Z <- t(apply(test.data, 1, function(n){(n - mean(n))/sd(n)}))

# Random forrest
Tree <- randomForest(x = t(as.matrix(train.data.Z)), y = train.labels, 
                     xtest = t(as.matrix(test.data.Z)), 
                     ytest = test.labels, keep.forest = TRUE)

# Prediction 
new.data <- log2(bulk[cur_markers,] + 1)
new.data.Z <- t(apply(new.data, 1, function(n){(n - mean(n))/sd(n)}))

pred.bulk <- predict(object = Tree, newdata = t(new.data.Z), type="prob")

# Collect day info on libraries
df <- data.frame(library = rownames(pred.bulk),
                 day = as.numeric(sub(" days", "", meta[rownames(pred.bulk),"Age"])))

pdf("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Supplemental_figures/Fig_S3/Bulkmapping_heatmap.pdf", 
    onefile = FALSE)
pheatmap(pred.bulk[order(df$day),], cluster_cols = FALSE, cluster_rows = FALSE,
         col = inferno(100),
         annotation_row = data.frame(row.names = rownames(pred.bulk),
                    sample = factor(df$day, levels = unique(df$day)[order(unique(df$day))])),
         labels_row = df$day[order(df$day)])
dev.off()

```
