---
title: "Figure S2"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_S2.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script recapitulates the visualization of replicates for B6 and P5 and the juvenile samples. 

# Load data and libraries

```{r data, message=FALSE}
# Libraries
library(scater)
library(ggplot2)
library(reshape2)
library(plyr)
library(openxlsx)
library(cowplot)
library(RColorBrewer)
library(pheatmap)
library(viridis)
library(irlba)
library(Rtsne)
source("../../Functions/auxiliary.R")

# Single cell data
sce.all <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all.rds")
sce.all <- sce.all[,colData(sce.all)$AnnotatedClusters != "Outliers"]
```

# Visualize the two batches for adult B6 and P5

```{r}
# Adult B6
B6 <- sce.all[,grepl("B6", colData(sce.all)$Sample)]

# Calculate tSNE
set.seed(12345)
B6 <- runTSNE(B6)

adult.batches <- ggplot(data.frame(tSNE1 = reducedDims(B6)$TSNE[,1],
                  tSNE2 = reducedDims(B6)$TSNE[,2],
                  batch = colData(B6)$Library)) + 
  geom_point(aes(tSNE1, tSNE2, colour = batch, size = batch)) +
  scale_colour_manual(values = c("dodgerblue4", "firebrick1")) +
  scale_size_manual(values = c(3,1)) + 
  theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_blank(), axis.ticks = element_blank(),
          axis.title = element_text(size = 12, face = "bold")) + ggtitle("B6")

# P5
P5 <- sce.all[,grepl("P5", colData(sce.all)$Sample)]

# Calculate tSNE
set.seed(12345)
P5 <- runTSNE(P5)

P5.batches <- ggplot(data.frame(tSNE1 = reducedDims(P5)$TSNE[,1],
                  tSNE2 = reducedDims(P5)$TSNE[,2],
                  batch = colData(P5)$Library)) + 
  geom_point(aes(tSNE1, tSNE2, colour = batch, size = batch)) +
  scale_colour_manual(values = c("dodgerblue", "firebrick4")) +
  scale_size_manual(values = c(3,1)) + 
  theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_blank(), axis.ticks = element_blank(),
          axis.title = element_text(size = 12, face = "bold")) + ggtitle("P5")
```

# Visualize all samples together

```{r}
# tSNE all samples 
cur_color_vector <- brewer.pal(10,"Paired")

# Before batch correction
# Highly variable genes
HVgenes <- HVG(sce = sce.all[Matrix::rowMeans(logcounts(sce.all)) > 0.1,])

set.seed(12345)
pca <- prcomp_irlba(t(logcounts(sce.all[HVgenes,])), n = 50)
tsne <- Rtsne(pca$x, pca = FALSE)

samples.before <- ggplot(data = data.frame(tSNE1 = tsne$Y[,1],
                         tSNE2 = tsne$Y[,2],
                         sample = colData(sce.all)$Sample)) +
    geom_point(aes(tSNE1, tSNE2, colour = sample), size = 0.5) +
    scale_color_manual(values = cur_color_vector) + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_blank(), axis.ticks = element_blank(),
          axis.title = element_text(size = 12, face = "bold"), 
          line = element_blank()) + ggtitle("Samples")

# After batch correction
samples <- ggplot(data = data.frame(tSNE1 = reducedDims(sce.all)$TSNE[,1],
                         tSNE2 = reducedDims(sce.all)$TSNE[,2],
                         sample = colData(sce.all)$Sample)) +
    geom_point(aes(tSNE1, tSNE2, colour = sample), size = 0.5) +
    scale_color_manual(values = cur_color_vector) + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_blank(), axis.ticks = element_blank(),
          axis.title = element_text(size = 12, face = "bold"), 
          line = element_blank()) + ggtitle("Samples")

# tSNE all samples - clusters
cluster <- ggplot(data = data.frame(tSNE1 = reducedDims(sce.all)$TSNE[,1],
                         tSNE2 = reducedDims(sce.all)$TSNE[,2],
                         group = colData(sce.all)$AnnotatedClusters)) +
    geom_point(aes(tSNE1, tSNE2, colour = group), size = 0.5) +
    scale_color_manual(values = metadata(sce.all)$color_vector) + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_blank(), axis.ticks = element_blank(),
          axis.title = element_text(size = 12, face = "bold"), 
          line = element_blank()) + ggtitle("Cluster")

```

# Save final figure

```{r final}
A <- plot_grid(adult.batches + theme(legend.position = c(.8,.9)), P5.batches + theme(legend.position = c(.8,.9)), ncol = 2, nrow = 1)
B <- plot_grid(samples.before + theme(legend.position="none"), samples + theme(legend.position=c(.01,.05)), ncol = 2, nrow =1)
C <- plot_grid(cluster + theme(legend.position="none"), NULL, ncol = 2, nrow =1)
final <- plot_grid(A, B, C, ncol = 1, nrow = 3)

ggsave(filename = "../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Supplemental_figures/Fig_S2/Fig_S2.pdf", 
       final, width = 15, height = 20)
```
