---
title: "Figure S8"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_S8.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data and libraries

```{r data, message=FALSE}
library(scater)
library(plyr)
library(reshape2)
library(pheatmap)
library(viridis)
library(plot3D)
library(ggsci)
library(cowplot)
library(openxlsx)
library(VennDiagram)
source("../../Functions/auxiliary.R")

# Read in sce data
sce <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all.rds")
sce <- sce[,grepl("B6", colData(sce)$Sample) & 
             colData(sce)$AnnotatedClusters %in% levels(colData(sce)$AnnotatedClusters)[1:20]]
sce <- normalize(sce)

# Read in gene annotations
genenames <- read.table("../../Data/Mouse_genes.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE)
rownames(genenames) <- genenames$Gene.stable.ID
```

# Order cells over the differentiation time course

```{r ordering}
# Select Spermatids
sce.spermatids <- sce[, colData(sce)$AnnotatedClusters %in% 
                           paste("S", 1:11, sep = "")]
sce.spermatids <- normalize(sce.spermatids)

# Compute HVG
HVgenes <- HVG(sce.spermatids)

# Compute PCA
pca <- prcomp(t(logcounts(sce.spermatids)[HVgenes,]))

# Pseudo rank
prank <- PT(rd = pca$x[,1:3], 
            clusters = colData(sce.spermatids)$AnnotatedClusters,
            col_vector = metadata(sce.spermatids)$color_vector)
```

# Histone variants over spermiogenesis

Here, we visualize the histone variants taken from Kennani et al. Epigenetics & Chromatin, 2017.

```{r hist-var}
# Read in histone variants
Hist.all <- read.xlsx("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_5/Mouse_histones_annotated.xlsx")
rownames(Hist.all) <- Hist.all$Ensembl.Gene.ID

# Collect data for heatmap plotting
for.heatmap <- logcounts(sce.spermatids)[rownames(Hist.all),
                  order(prank[,"rank"], decreasing = TRUE)]
colnames(for.heatmap) <- paste(colData(sce.spermatids)$Barcode[order(prank[,"rank"],
                                                               decreasing = TRUE)],
                               colData(sce.spermatids)$Library[order(prank[,"rank"],
                                                               decreasing = TRUE)],
                               sep = "_")

# Plot these genes over pseudotime
pdf("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_5/Fig_5_HistoneVariants.pdf", onefile = FALSE)
pheatmap(for.heatmap, show_colnames = FALSE, show_rownames = FALSE,
         cluster_rows = FALSE, cluster_cols = FALSE, 
         color = colorRampPalette(c("#053061", "#4393c3", "#f7f7f7", "#d6604d", "#67001f"))(100),
         annotation_col = data.frame(row.names = colnames(for.heatmap),
                  cell_type = colData(sce.spermatids)$AnnotatedClusters[order(prank[,"rank"],
                      decreasing = TRUE)]),
         annotation_colors = list(cell_type = metadata(sce.spermatids)$color_vector,
                                  label = c("NA" = "white",
                                            "label" = "black"),
                                  Histone = c("H2A_variant" = "springgreen",
                                              "H2B_variant" = "springgreen3",
                                              "H3_variant" = "seagreen",
                                              "H1_variant" = "lightseagreen",
                                              "Canonical" = "indianred3",
                                              "Transition_protein" = "darkorange4",
                                              "Protamine" = "burlywood4"),
                                  Testis_specific = c("Testis-specific" = "sienna1",
                                                      "NA" = "white")), 
         scale = "row",
         annotation_row = data.frame(row.names = rownames(for.heatmap),
                                     Testis_specific = Hist.all$`Testis-specific`,
                                     Histone = Hist.all$Label,
                                     label = Hist.all$Gene_name))
dev.off()
```

# Visualize histone variants

```{r}
p.clusters <- ggplot(data.frame(tSNE1 = reducedDims(sce)$TSNE[,1],
                      tSNE2 = reducedDims(sce)$TSNE[,2],
                      cluster = colData(sce)$AnnotatedClusters)) +
      geom_point(aes(tSNE1, tSNE2, colour = cluster)) + 
      scale_color_manual(values = metadata(sce)$color_vector) + 
  guides(colour = FALSE)

# H3f3a
H3f3a.tsne <- ggplot(data.frame(tSNE1 = reducedDims(sce)$TSNE[,1],
                      tSNE2 = reducedDims(sce)$TSNE[,2],
                      Gene = logcounts(sce)[rowData(sce)$Symbol == "H3f3a",])) +
      geom_point(aes(tSNE1, tSNE2, colour = Gene)) + 
      scale_color_viridis() 

H3f3a.box <-  ggplot(data.frame(value = logcounts(sce)[rowData(sce)$Symbol == "H3f3a",],
                      cluster = colData(sce)$AnnotatedClusters)) +
      geom_boxplot(aes(x = cluster, y = value, fill = cluster)) + 
      scale_fill_manual(values = metadata(sce)$color_vector) + ylab("log2(Expr)") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            panel.background = element_blank(), 
            axis.title.x = element_blank()) + guides(fill = FALSE) +
  ylim(c(0,9))

# H3f3b
H3f3b.tsne <- ggplot(data.frame(tSNE1 = reducedDims(sce)$TSNE[,1],
                      tSNE2 = reducedDims(sce)$TSNE[,2],
                      Gene = logcounts(sce)[rowData(sce)$Symbol == "H3f3b",])) +
      geom_point(aes(tSNE1, tSNE2, colour = Gene)) + 
      scale_color_viridis() 

H3f3b.box <-  ggplot(data.frame(value = logcounts(sce)[rowData(sce)$Symbol == "H3f3b",],
                      cluster = colData(sce)$AnnotatedClusters)) +
      geom_boxplot(aes(x = cluster, y = value, fill = cluster)) + 
      scale_fill_manual(values = metadata(sce)$color_vector) + ylab("log2(Expr)") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            panel.background = element_blank(), 
            axis.title.x = element_blank()) + guides(fill = FALSE) +
  ylim(c(0,9))

# Hist1h4a 
Hist1h4a.tsne <- ggplot(data.frame(tSNE1 = reducedDims(sce)$TSNE[,1],
                      tSNE2 = reducedDims(sce)$TSNE[,2],
                      Gene = logcounts(sce)[rowData(sce)$Symbol == "Hist1h4a",])) +
      geom_point(aes(tSNE1, tSNE2, colour = Gene)) + 
      scale_color_viridis() 

Hist1h4a.box <-  ggplot(data.frame(value = logcounts(sce)[rowData(sce)$Symbol == "Hist1h4a",],
                      cluster = colData(sce)$AnnotatedClusters)) +
      geom_boxplot(aes(x = cluster, y = value, fill = cluster)) + 
      scale_fill_manual(values = metadata(sce)$color_vector) + ylab("log2(Expr)") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1),
            panel.background = element_blank(), 
            axis.title.x = element_blank()) + guides(fill = FALSE) +
  ylim(c(0,5))
```

# Save figure

```{r}
final <- plot_grid(p.clusters, H3f3a.tsne, H3f3b.tsne, 
          NULL, H3f3a.box, H3f3b.box,
          Hist1h4a.tsne, Hist1h4a.box, NULL, ncol = 3,
          nrow = 3)
ggsave("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_S6/Fig_S6.pdf", final, width = 12, height = 12)
```