---
title: "Figure S6"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_S6.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r data, message=FALSE}
library(scater)
library(ggplot2)
library(reshape2)
library(plyr)
library(openxlsx)
library(cowplot)
library(viridis)
library(pheatmap)
source("../../Functions/auxiliary.R")
```

# Visualize the quantification of Prss50

```{r}
Prss50.quant <- read.xlsx("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/RNAScope/RNAscope_quantification.xlsx", 
                         sheet = 6)
Prss50.quant$Sample <- sapply(Prss50.quant$X1, function(n){unlist(strsplit(n, " -"))[1]})
Prss50.quant$Sample <- factor(Prss50.quant$Sample, levels = unique(Prss50.quant$Sample))

# Save figure
quant.plot <- ggplot(Prss50.quant) + 
  geom_bar(aes(Sample, Signal.Count.Per.um2, fill = X1), stat = "identity",
           width = 0.75, 
           position = "dodge") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  ylab("Dots per um2") + xlab("Tubule stage") + scale_fill_brewer(palette = "Paired")

ggsave("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Supplemental_figures/Fig_S6/Prss50.pdf", quant.plot, width = 5, height = 3)

# Visualize Prss50 signal in different epithelial stages

Prss50.quant_adult <- read.xlsx("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/RNAScope/RNAscope_quantification.xlsx", 
                         sheet = 3)

Prss50.quant_adult <- Prss50.quant_adult[!is.na(Prss50.quant_adult$X1),]
Prss50.quant_adult$X1 <- factor(Prss50.quant_adult$X1, levels = Prss50.quant_adult$X1)

# Save figure
quant.plot <- ggplot(Prss50.quant_adult) + 
  geom_col(aes(X1, Signal.Count.Per.um2), fill = "steelblue", col = "black", width = 0.75) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  ylab("Dots per um2") + xlab("Tubule stage")

ggsave("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Supplemental_figures/Fig_S6/Prss50_Adult.pdf", quant.plot, width = 5, height = 3)
```

# Visualize emptyDrops

```{r emptyDrops}
# Single cell data
sce <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_emptyDrops.rds")
no.genes <- nexprs(sce, detection_limit = 0)

# Collect marker genes expression in correct order
df1 <- data.frame(tsne1 =reducedDims(sce)$TSNE[
                      colData(sce)$AnnotatedClusters != "NewCell",1],
                  tsne2 = reducedDims(sce)$TSNE[
                    colData(sce)$AnnotatedClusters != "NewCell",2],
                  batch = colData(sce)$AnnotatedClusters[
                    colData(sce)$AnnotatedClusters != "NewCell"
                  ],
                  sample = colData(sce)$Sample[
                    colData(sce)$AnnotatedClusters != "NewCell"
                  ],
                  no.genes = no.genes[
                  colData(sce)$AnnotatedClusters != "NewCell"])
df2 <- data.frame(tsne1 =reducedDims(sce)$TSNE[
                      colData(sce)$AnnotatedClusters == "NewCell",1],
                  tsne2 = reducedDims(sce)$TSNE[
                    colData(sce)$AnnotatedClusters == "NewCell",2],
                  batch = colData(sce)$AnnotatedClusters[
                    colData(sce)$AnnotatedClusters == "NewCell"
                  ],
                  sample = colData(sce)$Sample[
                    colData(sce)$AnnotatedClusters == "NewCell"
                  ],
                  no.genes = no.genes[
                  colData(sce)$AnnotatedClusters == "NewCell"])
  
# All samples
emptyDrops <- ggplot() +
  geom_point(data = df2, aes(tsne1, tsne2, colour = batch), size = 0.5) +
  geom_point(data = df1, aes(tsne1, tsne2, colour = batch), size = 0.5) +
  scale_color_manual(values = metadata(sce)$color_vector) +
  guides(colour = FALSE)

# Number of genes expressed
emptyDrops.no.genes <- ggplot() +
  geom_point(data = df2, aes(tsne1, tsne2, colour = no.genes), size = 0.5) +
  geom_point(data = df1, aes(tsne1, tsne2, colour = no.genes), size = 0.5) +
  scale_color_gradientn(colours = inferno(100))
```

# Visualize different timepoints

```{r}
plot.list <- list()
for(i in unique(sce$Sample)){
  cur_df1 <- df1[df1$sample == i,]
  cur_df2 <- df2[df2$sample == i,]
  
  plot.list[[i]] <- ggplot() +
  geom_point(data = cur_df2, aes(tsne1, tsne2, colour = batch), size = 0.5) +
  geom_point(data = cur_df1, aes(tsne1, tsne2, colour = batch), size = 0.5) +
  scale_color_manual(values = metadata(sce)$color_vector) +
  guides(colour = FALSE) + 
  ylab("tSNE 2") + xlab("tSNE 1") + 
  ylim(floor(min(reducedDims(sce)$TSNE[,2])),
       ceiling(max(reducedDims(sce)$TSNE[,2]))) +
  xlim(floor(min(reducedDims(sce)$TSNE[,1])),
       ceiling(max(reducedDims(sce)$TSNE[,1]))) +  
  theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          axis.text = element_blank(), axis.ticks = element_blank(),
          axis.title = element_text(size = 12, face = "bold"))
}
```

# Save final figure

```{r save}
A <- plot_grid(emptyDrops, emptyDrops.no.genes,
               ncol = 2, nrow = 1)
B <- plot_grid(plot.list[[2]], plot.list[[3]], plot.list[[4]], plot.list[[5]], 
                   plot.list[[6]], plot.list[[7]], plot.list[[8]], plot.list[[1]], 
               ncol = 4, nrow = 2)
final <- plot_grid(A, B, ncol = 1, nrow = 2)

ggsave("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Supplemental_figures/Fig_S6/Fig_S6.pdf", final,
       width = 10, height = 12)
```