---
title: "Removal of outlying cell types per group"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read data and libraries

```{r}
library(scater)
library(Rtsne)
library(Matrix)
library(scran)
library(viridis)

sce <- readRDS("../../data/10X_data/SCE_all_unfiltered.rds")
```

# Group 1

```{r}
group = "1"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```

# Group 2

```{r}
group = "2"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1, k = 10)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```

# Group 3

```{r}
group = "3"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,1] < -10]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```

# Group 4

```{r}
group = "4"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,1] > 7.5 | (tsne$Y[,1] < -10)]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```

# Group 5

```{r}
group = "5"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,2] > 12]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 6

```{r}
group = "6"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,1] < 10 & tsne$Y[,1] > -15 & tsne$Y[,2] > 5]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 7

```{r}
group = "7"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,1] < -10]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 8

```{r}
group = "8"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,1] > 4 & tsne$Y[,2] > 2]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 9

```{r}
group = "9"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,2] < - 7.5]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 10

```{r}
group = "10"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```
# Group 11

```{r}
group = "11"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,1] > -2.5 & tsne$Y[,2] > 7.5]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 12

```{r}
group = "12"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```
# Group 13

```{r}
group = "13"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```
# Group 14

```{r}
group = "14"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,2] > 6 & tsne$Y[,1] < 0]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 15

```{r}
group = "15"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```
# Group 16

```{r}
group = "16"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```
# Group 17

```{r}
group = "17"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,1] > 6]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 18

```{r}
group = "18"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,2] < -7.5]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 19

```{r}
group = "19"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```
# Group 20

```{r}
group = "20"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```
# Group 21

```{r}
group = "21"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,1] < -10 & tsne$Y[,2] > 7.5]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```
# Group 22

```{r}
group = "22"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()

# Filter outliers
barcodes <- c(colData(cur_sce.B6)$Barcode, 
              colData(cur_sce.Tc0.1)$Barcode,
              colData(cur_sce.Tc0.2)$Barcode,
              colData(cur_sce.Tc1.1)$Barcode,
              colData(cur_sce.Tc1.2)$Barcode)[tsne$Y[,2] < -6]
colData(sce)$Cluster[match(barcodes, colData(sce)$Barcode)] <- "Outliers"
```

# Group 23

```{r}
group = "23"

cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample) & colData(sce)$Cluster == group]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1, k=2)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",colData(sce)$Cluster == group],
  sample = colData(sce)$Sample[colData(sce)$Cluster == group])) +
  geom_point(aes(tSNE1, tSNE2, colour = gene, shape = sample)) +
  scale_color_viridis() + theme_minimal()
```

# Visualize all

```{r}
cur_sce.B6 <- sce[,grepl("B6", colData(sce)$Sample)]
cur_sce.B6 <- normalize(cur_sce.B6)
cur_sce.Tc0.1 <- sce[,grepl("Tc0_do15984", colData(sce)$Sample)]
cur_sce.Tc0.1 <- normalize(cur_sce.Tc0.1)
cur_sce.Tc0.2 <- sce[,grepl("Tc0_do17622", colData(sce)$Sample)]
cur_sce.Tc0.2 <- normalize(cur_sce.Tc0.2)
cur_sce.Tc1.1 <- sce[,grepl("Tc1_do15983", colData(sce)$Sample)]
cur_sce.Tc1.1 <- normalize(cur_sce.Tc1.1)
cur_sce.Tc1.2 <- sce[,grepl("Tc1_do17623", colData(sce)$Sample)]
cur_sce.Tc1.2 <- normalize(cur_sce.Tc1.2)

# Compute highly variable genes
HVG.B6 <- trendVar(cur_sce.B6, use.spikes = FALSE)
HVG.B6.1 <- decomposeVar(cur_sce.B6, HVG.B6)
HVG.Tc0.1 <- trendVar(cur_sce.Tc0.1, use.spikes = FALSE)
HVG.Tc0.1.1 <- decomposeVar(cur_sce.Tc0.1, HVG.Tc0.1)
HVG.Tc0.2 <- trendVar(cur_sce.Tc0.2, use.spikes = FALSE)
HVG.Tc0.2.1 <- decomposeVar(cur_sce.Tc0.2, HVG.Tc0.2)
HVG.Tc1.1 <- trendVar(cur_sce.Tc1.1, use.spikes = FALSE)
HVG.Tc1.1.1 <- decomposeVar(cur_sce.Tc1.1, HVG.Tc1.1)
HVG.Tc1.2 <- trendVar(cur_sce.Tc1.2, use.spikes = FALSE)
HVG.Tc1.2.1 <- decomposeVar(cur_sce.Tc1.2, HVG.Tc1.2)

HVG.df <- combineVar(HVG.B6.1, HVG.Tc0.1.1, HVG.Tc0.2.1, HVG.Tc1.1.1, HVG.Tc1.2.1)
HVG.df <- HVG.df[order(HVG.df$bio, decreasing = TRUE),]
HVG <- rownames(HVG.df)[1:1000]

# Batch correction
corrected <- mnnCorrect(as.matrix(logcounts(cur_sce.B6)[HVG,]), 
                        as.matrix(logcounts(cur_sce.Tc0.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc0.2)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.1)[HVG,]),
                        as.matrix(logcounts(cur_sce.Tc1.2)[HVG,]),
                        cos.norm.in = TRUE, cos.norm.out = TRUE, sigma = 0.1, k=2)

set.seed(123)
tsne <- Rtsne(t(cbind(corrected$corrected[[1]], 
                      corrected$corrected[[2]],
                      corrected$corrected[[3]],
                      corrected$corrected[[4]],
                      corrected$corrected[[5]])))

# Prm1
ggplot(data = data.frame(
  tSNE1 = tsne$Y[,1], tSNE2 = tsne$Y[,2], 
  gene = logcounts(sce)["ENSMUSG00000022501",],
  sample = colData(sce)$Sample,
  cluster = colData(sce)$Cluster)) +
  geom_point(aes(tSNE1, tSNE2, colour = cluster, shape = sample)) + theme_minimal()
```

# Save file

```{r}
saveRDS(sce, "../../data/10X_data/SCE_all.rds")
```