---
title: "Batch correction"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Preprocessing/QualityControl/Batch_correction.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the data

```{r data, message=FALSE}
library(scran)
library(scater)
library(Rtsne)
library(RColorBrewer)
library(viridis)
source("../../Functions/auxiliary.R")

sce.all <- readRDS("/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all_QC.rds")
```

# Batch correction

```{r correction}
# Split datasets into batches
sce.single <- split.sce(sce = sce.all, groups = unique(colData(sce.all)$Sample), 
                        colData.name = "Sample")

# Batch correction
corrected <- batch.correction(sce.single)

# Save batch corrected matrix in sce object
metadata(sce.all)$corrected <- corrected
```

# Visualize batch corrected data

```{r visualizataion}
set.seed(111)
tsne <- Rtsne(t(metadata(sce.all)$corrected), perplexity = 60)
reducedDims(sce.all)$TSNE <- tsne$Y

# Batches
col_vector <- c(brewer.pal(8, "Set1"), brewer.pal(8, "Set2"), brewer.pal(8, "Set3"))
ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  batch = colData(sce.all)$Sample)) +
  geom_point(aes(tsne1, tsne2, colour = batch)) +
  scale_color_manual(values = col_vector)

# Verification of chr21 expression: PDXK
# PDXK 
ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  gene = logcounts(sce.all)[rowData(sce.all)$ID[rowData(sce.all)$Symbol == "PDXK"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene))

# Library size
ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  gene = colData(sce.all)$log10_total_counts)) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_colour_viridis()

# Number genes expressed
ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  gene = colData(sce.all)$total_features)) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_colour_viridis()

# Mitochondrial genes
mt <- read.table("../../Data/Mouse_genes.txt", sep = "\t", header = TRUE,
                 stringsAsFactors = FALSE)
mt <- mt[mt$Chromosome.scaffold.name == "MT",]
ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  mito = Matrix::colSums(counts(sce.all)[rowData(sce.all)$ID %in%
                                                mt$Gene.stable.ID,])/
                    Matrix::colSums(counts(sce.all)))) + geom_point(aes(tsne1, tsne2, colour = mito)) + scale_colour_viridis()

# Stra8 
ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  gene = logcounts(sce.all)[rowData(sce.all)$ID[rowData(sce.all)$Symbol == "Stra8"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_colour_viridis()

# Defb19 
ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  gene = logcounts(sce.all)[rowData(sce.all)$ID[rowData(sce.all)$Symbol == "Defb19"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_colour_viridis()

# Prm1 
ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  gene = logcounts(sce.all)[rowData(sce.all)$ID[rowData(sce.all)$Symbol == "Prm1"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_colour_viridis()

# Dazl 
  ggplot(data.frame(tsne1 = reducedDims(sce.all)$TSNE[,1],
                  tsne2 = reducedDims(sce.all)$TSNE[,2],
                  gene = logcounts(sce.all)[rowData(sce.all)$ID[rowData(sce.all)$Symbol == "Dazl"],])) +
  geom_point(aes(tsne1, tsne2, colour = gene)) + scale_colour_viridis()

```

```{r save}
saveRDS(sce.all, "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all_BatchCorrected.rds")
```