---
title: "Figure 2"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_2.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data and libraries

```{r data, message=FALSE}
# Libraries
library(scater)
library(ggplot2)
library(reshape2)
library(plyr)
library(nnet)
library(randomForest)
library(openxlsx)
library(cowplot)
library(pheatmap)
library(viridis)
library(irlba)
library(Rtsne)
source("../Functions/auxiliary.R")

# Single cell data
sce.all <- readRDS("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all.rds")
sce.all <- sce.all[,!(colData(sce.all)$Sample %in% c("Tc1", "Tc0"))]

# Bulk data
bulk <- readRDS("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/bulk/norm/1st_wave_bulk_norm_reverse-stranded.rds")

# Meta info
meta <- read.table("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Tables/BulkSamples_stats.txt", sep = "\t")
```

# Ratios of cell types in each sample

```{r ratios}
# Calculate proprtions of cell types in each sample
df <- data.frame(sample = sub("_.*", "", colData(sce.all)$Sample),
                 group = colData(sce.all)$AnnotatedClusters,
                 value = rep(1, ncol(sce.all)))

proportions <- with(df, table(sample, group))/plyr::count(df = df, vars = "sample")$freq

# Sum across Fetal Leydig cells
proportions <- cbind(proportions, rowSums(proportions[,grepl("Fetal_Leydig", colnames(proportions))]))
proportions <- proportions[c("B6", "P5", "P10", "P15", "P20", "P25", "P30", "P35"),
                           c(1:22, 23, 24, 32)]
colnames(proportions)[25] <- "Fetal_Leydig" 
```

# Visualize percentages for germ cells

```{r, visualization}
cur_df.melt <- melt(proportions)
levels(cur_df.melt$Var1) <- rev(c("B6", "P5", "P10", "P15", "P20", "P25", "P30", "P35"))
levels(cur_df.melt$Var2) <- colnames(proportions)

proportions.p <- ggplot(cur_df.melt) + 
  geom_point(aes(Var2, rev(Var1), size = value, fill = Var2), shape = 22) +
  scale_fill_manual(values = c(metadata(sce.all)$color_vector,
        "Fetal_Leydig" = as.character(metadata(sce.all)$color_vector["Fetal_Leydig_1"]))) + 
  theme(panel.background = element_blank(), axis.title = element_blank(),
        axis.text.x = element_text(angle = 45, size = 12, hjust = 1),
        axis.text.y = element_text(size = 12)) +
  scale_size_area(max_size = 15) + guides(colour = FALSE)

# Save plot
ggsave(filename = "../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Fig_2/Fig_2_proportions.pdf", proportions.p,
       width = 320, units = "mm", height = 130)
```


# Map bulk libraries to stages

We perform a random forrest regression approach between the cluster labels 
and the top 50 marker genes for each group. The training is performed on adult B6 samples

```{r bulk mapping}
# Load marker genes
marker.genes <- readRDS("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/Results/Marker_genes/Marker_genes_B6.rds")
cur_markers <- as.character(unlist(lapply(marker.genes, function(n){rownames(n)[1:50]})))
cur_markers <- cur_markers[cur_markers %in% rownames(bulk)]

# Train the classifier on adult B6 - remove outliers, unannotated cells and endothelia cells
sce.B6 <- sce.all[,grepl("B6", colData(sce.all)$Sample) & 
                    !(colData(sce.all)$AnnotatedClusters %in% 
             c("Outliers", "Endothelial_cells"))]
sce.B6 <- normalize(sce.B6)
labels <- factor(colData(sce.B6)$AnnotatedClusters,
                    levels = levels(colData(sce.B6)$AnnotatedClusters)[
                      levels(colData(sce.B6)$AnnotatedClusters) %in%
                        unique(colData(sce.B6)$AnnotatedClusters)])

# Create training and testing datasets
set.seed(1234)
sam <- sample(1:ncol(sce.B6), 2000)
#train.data <- data.frame(t(as.matrix(logcounts(sce.B6)[cur_markers,sam])))
#train.data$labels <- labels[sam] 
#test.data <- data.frame(t(as.matrix(logcounts(sce.B6)[cur_markers,-sam])))
#test.data$labels <- labels[-sam] 

train.data <- as.matrix(logcounts(sce.B6)[cur_markers,sam])
train.labels <- labels[sam] 
test.data <- as.matrix(logcounts(sce.B6)[cur_markers,-sam])
test.labels <- labels[-sam] 

# logistic regression
#model <- multinom(labels ~ ., data = train.data, MaxNWts = 40000, maxit = 1000)

# Scale the counts prior to training
# Z score
train.data.Z <- t(apply(train.data, 1, function(n){(n - mean(n))/sd(n)}))
test.data.Z <- t(apply(test.data, 1, function(n){(n - mean(n))/sd(n)}))

# Random forrest
Tree <- randomForest(x = t(as.matrix(train.data.Z)), y = train.labels, 
                     xtest = t(as.matrix(test.data.Z)), 
                     ytest = test.labels, keep.forest = TRUE)

# Prediction 
new.data <- log2(bulk[cur_markers,] + 1)
new.data.Z <- t(apply(new.data, 1, function(n){(n - mean(n))/sd(n)}))

pred.bulk <- predict(object = Tree, newdata = t(new.data.Z), type="prob")

# Collect day info on libraries
df <- data.frame(library = rownames(pred.bulk),
                 day = as.numeric(sub(" days", "", meta[rownames(pred.bulk),"Age"])))

pdf("../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Fig_2/Fig_2_bulkmapping_heatmap.pdf", 
    onefile = FALSE)
pheatmap(pred.bulk[order(df$day),], cluster_cols = FALSE, cluster_rows = FALSE,
         col = inferno(100),
         annotation_row = data.frame(row.names = rownames(pred.bulk),
                    sample = factor(df$day, levels = unique(df$day)[order(unique(df$day))])),
         labels_row = df$day[order(df$day)])
dev.off()

```

# Map RA cells to adult trajectory

```{r RA-blocked}
# Data from Chen et al, Cell Research
sce_RA <- readRDS("../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_RA.rds")
genes <- intersect(rownames(sce_RA), rowData(sce.B6)$Symbol)

sce <- sce.B6[match(genes, rowData(sce.B6)$Symbol),]
rownames(sce) <- genes
sce_RA <- sce_RA[genes,]

# Select only the germ cells
sce <- sce[,grepl("Spermatogonia|Spermatocytes|S1|S2|S3|S4|S5|S6|S7|S8|S9", colData(sce)$AnnotatedClusters)]
sce <- normalize(sce)

# Select cells from RA blocked cells that are represented in adult trajectory
sce_all_RA <- sce_RA[,colData(sce_RA)$cell_type %in% 
                       c("A1", "ln", "TypeBS", "TypeBG2M", "G1", "L", "Z", "eP", "mP", "mPL", 
                         "lPL", "lP", "D", "MI", "MII", "RS1o2", "RS3o4", "RS5o6", "RS7o8")]
sce_all_RA <- normalize(sce_all_RA)

# Batch correction
sce.single <- split.sce(sce = sce, groups = unique(colData(sce)$Library), 
                        colData.name = "Library")
sce.single$RA <- sce_all_RA

corrected <- batch.correction(sce.single)

# Visualization
set.seed(123)
pca <- prcomp_irlba(t(corrected), n = 50)
tsne <- Rtsne(pca$x, pca = FALSE, perplexity = 50)

# Create new colour vector
colour_vector_RA <- c("A1" = "#67001f",
                      "TypeBS" = "#49006a",
                      "ePL" = "#800026", 
                      "G1" = "#ae017e",        
                      "mPL" = "#fc4e2a",       
                      "eP" = "#084081",        
                      "D" = "#2171b5",    
                      "mP" = "#4eb3d3",     
                      "RS1o2" = "#014636",  
                      "TypeBG2M" = "#e7298a",
                      "lPL" = "#fed976",      
                      "MI" = "#807dba",       
                      "RS7o8" = "#74c476",    
                      "Z" = "#fe9929",   
                      "MII" = "#dadaeb",     
                      "L" = "#662506",      
                      "lP" = "#ccebc5",      
                      "ln" = "#fde0dd",        
                      "RS3o4" = "#3690c0",      
                      "RS5o6" = "#a6bddb")

col_vector <- c(metadata(sce)$color_vector, colour_vector_RA)

tSNE_RA <- ggplot() +
  geom_point(data = data.frame(tSNE1 = tsne$Y[(ncol(sce)+1):(ncol(sce)+ncol(sce_all_RA)),1],
                  tSNE2 = tsne$Y[(ncol(sce)+1):(ncol(sce)+ncol(sce_all_RA)),2],
                  cell_type = colData(sce_all_RA)$cell_type),
             aes(tSNE1, tSNE2, colour = cell_type), size = 1.5, shape = 8) +
  geom_point(data = data.frame(tSNE1 = tsne$Y[1:ncol(sce),1],
                  tSNE2 = tsne$Y[1:ncol(sce),2],
                  cluster = colData(sce)$AnnotatedClusters),
             aes(tSNE1, tSNE2, colour = cluster), size = 0.5) + 
  scale_color_manual(values = col_vector)

ggplot() +
  geom_point(data = data.frame(PC1 = pca$x[(ncol(sce)+1):(ncol(sce)+ncol(sce_all_RA)),1],
                  PC2 = pca$x[(ncol(sce)+1):(ncol(sce)+ncol(sce_all_RA)),2],
                  cell_type = colData(sce_all_RA)$cell_type),
             aes(PC1, PC2, colour = cell_type, size = 1.5, alpha = 0.75), shape = 8) +
  geom_point(data = data.frame(PC1 = pca$x[1:ncol(sce),1],
                  PC2 = pca$x[1:ncol(sce),2],
                  cluster = colData(sce)$AnnotatedClusters),
             aes(PC1, PC2, colour = cluster)) + 
  scale_color_manual(values = col_vector)

ggsave(filename = "../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Results/New_figures/Fig_2/Fig_2_RA_cells.pdf", tSNE_RA,
       width = 250, units = "mm", height = 130)
```
