---
title: "Figure S2"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_3.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This figure analyses the different cell populations in the P10 sample.

# Load data and libraries

```{r data, message=FALSE}
# Libraries
library(scater)
library(ggplot2)
library(reshape2)
library(plyr)
library(openxlsx)
library(cowplot)
library(viridis)
source("../Functions/auxiliary.R")

# Single cell data
sce <- readRDS("/Users/eling01/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all_clusters.rds")

# Select spermatogonia and spermatocytes
sce <- sce[,grepl("B6", colData(sce)$Sample) &
             colData(sce)$AnnotatedClusters %in% c("Spermatogonia", "Early_Spermatocytes_1",
                                                   "Early_Spermatocytes_2", "Mid_Spermatocytes_1",
                                                   "Mid_Spermatocytes_2", "Late_Spermatocytes_1",
                                                   "Late_Spermatocytes_2",  "Meiosis")]
sce <- normalize(sce)
```

# Spermatogonia 

```{r spermatogonia}
sce.spermatogonia <- sce[,colData(sce)$AnnotatedClusters == "Spermatogonia"]
sce.spermatogonia <- normalize(sce.spermatogonia)

# Compute HVG
HVgenes <- HVG(sce.spermatogonia)

# Compute PCA
pca.spermatogonia <- prcomp(t(logcounts(sce.spermatogonia)[HVgenes,])) 

# Save rotations of pca
rots.PC1 <- data.frame(row.names = rownames(pca.spermatogonia$rotation),
  rotations = pca.spermatogonia$rotation[,1],
  genenames = rowData(sce.spermatogonia)$Symbol[match(rownames(pca.spermatogonia$rotation),
                                                      rowData(sce.spermatogonia)$ID)])
rots.PC1 <- rots.PC1[order(rots.PC1$rotations, decreasing = TRUE),]

write.xlsx(rots.PC1, "/Users/eling01/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/10X/SpermatogoniaPCARotations.xlsx")

# Visualize marker genes

Nanos3.p <- ggplot(data.frame(PC1 = pca.spermatogonia$x[,1],
                  PC2 = pca.spermatogonia$x[,2],
                  Nanos3 =  logcounts(sce.spermatogonia)[rowData(sce.spermatogonia)$Symbol == "Nanos3",])) +
  geom_point(aes(PC1, PC2, colour = Nanos3)) + scale_colour_viridis()

Stra8.p <- ggplot(data.frame(PC1 = pca.spermatogonia$x[,1],
                  PC2 = pca.spermatogonia$x[,2],
                  Stra8 =  logcounts(sce.spermatogonia)[rowData(sce.spermatogonia)$Symbol == "Stra8",])) +
  geom_point(aes(PC1, PC2, colour = Stra8)) + scale_colour_viridis()

Rhox13.p <- ggplot(data.frame(PC1 = pca.spermatogonia$x[,1],
                  PC2 = pca.spermatogonia$x[,2],
                  Rhox13 =  logcounts(sce.spermatogonia)[rowData(sce.spermatogonia)$Symbol == "Rhox13",])) +
  geom_point(aes(PC1, PC2, colour = Rhox13)) + scale_colour_viridis()

spermatogonia.p <- plot_grid(Nanos3.p, Stra8.p, Rhox13.p, ncol = 3, nrow = 1)
```

# Spermatocytes

# Order cells in pseudotime

```{r PT}
sce.spermatocytes <- sce[, colData(sce)$AnnotatedClusters %in% c("Early_Spermatocytes_1",
                                                   "Early_Spermatocytes_2", "Mid_Spermatocytes_1",
                                                   "Mid_Spermatocytes_2", "Late_Spermatocytes_1",
                                                   "Late_Spermatocytes_2",  "Meiosis")]
sce.spermatocytes <- normalize(sce.spermatocytes)

# Compute HVG
HVgenes <- HVG(sce.spermatocytes)

# Compute PCA
pca <- prcomp(t(logcounts(sce.spermatocytes)[HVgenes,]))

# Pseudo rank
prank <- PT(rd = pca$x[,1:3], clusters = colData(sce.spermatocytes)$AnnotatedClusters,
            col_vector = metadata(sce.spermatocytes)$color_vector)

```


```{r}
PT <-  prank[,"lambda"]

set.seed(123)
y = rnorm(length(PT), mean = 0, sd = 0.01)

p.PT <- ggplot(data.frame(x = PT,
                  y = y,
                  group = colData(sce.spermatocytes)$AnnotatedClusters)) +
  geom_point(aes(x, y , fill = group), shape = 21, size = 3) + 
  scale_fill_manual(values = metadata(sce.spermatocytes)$color_vector) + ylim(c(-0.033,0.033)) +
  theme(legend.position = "none", panel.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), axis.title.y = element_blank(), 
        axis.title.x = element_blank(), axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(), axis.line.y = element_blank(),
        axis.text.y = element_blank(), axis.ticks.y = element_blank())

# Plot marker genes
genes <- c("Dazl", "Piwil1", "Pou5f2", "Aurkc")
all.max <- max(logcounts(sce.spermatocytes)[rowData(sce.spermatocytes)$ID[match(genes, rowData(sce.spermatocytes)$Symbol)],])

# Dazl
Dazl.p <- ggplot(data.frame(x = PT,
                  y = y,
                  gene = logcounts(sce.spermatocytes)[rowData(sce.spermatocytes)$ID[match(genes[1],
                                           rowData(sce.spermatocytes)$Symbol)],])) +
  geom_point(aes(x, y , fill = gene), shape = 21, size = 3) + 
  scale_fill_viridis(name = NULL) + ylim(c(-0.033,0.033)) + 
  ylab(genes[1]) +
  theme(panel.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), axis.text.y = element_blank(), 
        axis.title.x = element_blank(), axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(), axis.line.y = element_blank(),
        axis.title.y = element_text(size = 15, face = "bold"), axis.ticks.y = element_blank(),
        axis.line.x = element_blank())

# Piwil1
Piwil1.p <- ggplot(data.frame(x = PT,
                  y = y,
                  gene = logcounts(sce.spermatocytes)[rowData(sce.spermatocytes)$ID[match(genes[2],
                                           rowData(sce.spermatocytes)$Symbol)],])) +
  geom_point(aes(x, y , fill = gene), shape = 21, size = 3) + 
  scale_fill_viridis(name = NULL) + ylim(c(-0.033,0.033)) + 
  ylab(genes[2]) +
  theme(panel.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), axis.text.y = element_blank(), 
        axis.title.x = element_blank(), axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(), axis.line.y = element_blank(),
        axis.title.y = element_text(size = 15, face = "bold"), axis.ticks.y = element_blank(),
        axis.line.x = element_blank())

# Pou5f2
Pou5f2.p <- ggplot(data.frame(x = PT,
                  y = y,
                  gene = logcounts(sce.spermatocytes)[rowData(sce.spermatocytes)$ID[match(genes[3],
                                           rowData(sce.spermatocytes)$Symbol)],])) +
  geom_point(aes(x, y , fill = gene), shape = 21, size = 3) + 
  scale_fill_viridis(name = NULL) + ylim(c(-0.033,0.033)) + 
  ylab(genes[3]) +
  theme(panel.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), axis.text.y = element_blank(), 
        axis.title.x = element_blank(), axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(), axis.line.y = element_blank(),
        axis.title.y = element_text(size = 15, face = "bold"), axis.ticks.y = element_blank(),
        axis.line.x = element_blank())

# Aurkc
Aurkc.p <- ggplot(data.frame(x = PT,
                  y = y,
                  gene = logcounts(sce.spermatocytes)[rowData(sce.spermatocytes)$ID[match(genes[4],
                                           rowData(sce.spermatocytes)$Symbol)],])) +
  geom_point(aes(x, y , fill = gene), shape = 21, size = 3) + 
  scale_fill_viridis(name = NULL) + ylim(c(-0.033,0.033)) + 
  ylab(genes[4]) +
  theme(panel.background = element_blank(), 
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), axis.text.y = element_blank(), 
        axis.title.x = element_blank(), axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(), axis.line.y = element_blank(),
        axis.title.y = element_text(size = 15, face = "bold"), axis.ticks.y = element_blank(),
        axis.line.x = element_blank())

spermatocytes.p <- plot_grid(p.PT, Dazl.p, Piwil1.p, Pou5f2.p, Aurkc.p, ncol = 1, nrow = 5)
```

# Save final figure

```{r final}
final <- plot_grid(spermatogonia.p, spermatocytes.p, ncol = 1, nrow = 2)
ggsave(filename = "/Users/nils/Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Fig_2.pdf", final)
```
