---
title: "Bulk_RNAseq_QC_norm"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reverse-stranded gene counting

# Load the data

```{r}
# Load reads
raw_counts <- read.table("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/bulk/raw/1st_wave_bulk_all_reverse-stranded.txt", sep = "\t")

# Remove aged samples
raw_counts <- raw_counts[,!grepl("do18174|do18175", colnames(raw_counts))]

# Load library
library(DESeq2)

raw_counts <- raw_counts[,!is.na(raw_counts[1,])]

# Filter libraries
plot(log10(colSums(raw_counts)), pch = 16)

plot(as.numeric(raw_counts["__no_feature",]/colSums(raw_counts)), pch = 16)
plot(as.numeric(raw_counts["__ambiguous",]/colSums(raw_counts)), pch = 16)
plot(as.numeric(raw_counts["__too_low_aQual",]/colSums(raw_counts)), pch = 16)
plot(as.numeric(raw_counts["__not_aligned",]/colSums(raw_counts)), pch = 16)
plot(as.numeric(raw_counts["__alignment_not_unique",]/colSums(raw_counts)), pch = 16)

# Percentage of mapped counts
plot(as.numeric(colSums(raw_counts[!grepl("__", rownames(raw_counts)),])/colSums(raw_counts)), pch = 16)

# Total mapped counts
plot(log10(as.numeric(colSums(raw_counts[!grepl("__", rownames(raw_counts)),]))), pch = 16)

raw_counts <- raw_counts[rowSums(raw_counts) > 0,]
raw_counts <- raw_counts[!grepl("__", rownames(raw_counts)),]

write.table(raw_counts, "../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/raw_reads/All_raw_selected.txt", sep = "\t")
```

# Normalize

```{r}
dds <- DESeqDataSetFromMatrix(countData = raw_counts, 
                              colData = data.frame(row.names = colnames(raw_counts),
                                                   names = colnames(raw_counts)),
                              design = ~ names)

dds <- estimateSizeFactors(dds)
norm <- counts(dds, normalized = TRUE)

saveRDS(norm, "../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/bulk/norm/1st_wave_bulk_norm_reverse-stranded.rds")
write.table(norm, "../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/bulk/normalized.txt", sep = "\t")
```

# Save information of this data as supllementary table S1

```{r metainfo}
library(openxlsx)
# Read in metainfo
meta <- read.xlsx("../../../../Dropbox (Cambridge University)/SST_spermatocytes/ArrayExpress/Bulk/sdrf.xlsx")

stats.df <- data.frame(row.names = meta$Source.Name,
                       Tissue = meta$`Characteristics[tissue]`,
                       Age = paste(meta$`Characteristics.[Age]`, "days"))

write.table(stats.df, "../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/Figures/Tables/BulkSamples_stats.txt", 
            sep = "\t", row.names = TRUE, col.names = TRUE, quote = FALSE)
```