---
title: "RA blocked cells"
author: "Nils Eling"
date: "11/09/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script overlays germ cells isolated after RA blocking with the continuum of germ cells that we discovered. 
RA blocked cells can be downloaded from: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE107644

# Load data

```{r data}
library(scran)
library(scater)
library(Matrix)
library(ggplot2)
library(Rtsne)
library(RColorBrewer)
library(irlba)
source("../../Functions/auxiliary.R")

# Data from Chen et al, Cell Research
files <- list.files("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Revisions/Data/Chen_CellResearch/GSE107644_RAW/", full.names = TRUE)

all_cells <- lapply(as.list(files), function(n){
  cur_file <- read.table(n, sep = "\t", header = TRUE)
  rownames(cur_file) <- cur_file[,1]
  cur_file <- cur_file[,-1]
})

all_cells <- do.call("cbind", all_cells)

# Form a sce 
sce_RA <- SingleCellExperiment(assays=list(counts=Matrix::Matrix(as.matrix(all_cells), sparse = TRUE)))
colData(sce_RA)$time_point <- factor(as.character(sapply(colnames(sce_RA), 
                                                         function(n){unlist(strsplit(n, "_"))[1]})),
                                        levels = paste("SpSC", c(0, 2:37), sep = "")) 
colData(sce_RA)$cell_type <- as.character(sapply(colnames(sce_RA), function(n){unlist(strsplit(n, "_"))[2]})) 

# Juvenile and adult data
sce <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_emptyDrops.rds")
sce <- sce[,grepl("B6|P15|P25", colData(sce)$Sample)]
```

## Simple quality checks for Chen et al data

```{r QC}
sce_RA <- calculateQCMetrics(sce_RA)

ggplot(as.data.frame(colData(sce_RA))) + 
  geom_point(aes(total_features_by_counts, log10_total_counts, colour = time_point))

# Remove 2 cells with few features detected
sce_RA <- sce_RA[,colData(sce_RA)$total_features_by_counts > 1250]
```

## Normalization

```{r norm}
clusters <- quickCluster(sce_RA, method = "igraph", irlba.args = c("work" = 100), 
                         max.size = 2000)

sce_RA <- computeSumFactors(sce_RA, clusters=clusters)

sce_RA <- normalize(sce_RA, return_log = TRUE)

# Visaulize as tSNE
set.seed(12345)
sce_RA <- runTSNE(sce_RA)

ggplot(data.frame(tSNE1 = reducedDims(sce_RA)$TSNE[,1],
                  tSNE2 = reducedDims(sce_RA)$TSNE[,2],
                  time_point = colData(sce_RA)$time_point,
                  cell_type = colData(sce_RA)$cell_type)) +
  geom_point(aes(tSNE1, tSNE2, colour = time_point))

ggplot(data.frame(tSNE1 = reducedDims(sce_RA)$TSNE[,1],
                  tSNE2 = reducedDims(sce_RA)$TSNE[,2],
                  time_point = colData(sce_RA)$time_point,
                  cell_type = colData(sce_RA)$cell_type)) +
  geom_point(aes(tSNE1, tSNE2, colour = cell_type))
```

## Batch correction

```{r batch-correction}
sce <- sce[match(intersect(rownames(sce_RA), rowData(sce)$Symbol), rowData(sce)$Symbol),]
sce_RA <- sce_RA[match(intersect(rownames(sce_RA), rowData(sce)$Symbol), rownames(sce_RA)),]
rownames(sce_RA) <- rownames(sce)
rowData(sce_RA)$Symbol <- rowData(sce)$Symbol
rowData(sce_RA)$ID <- rowData(sce)$ID
sce.single <- split.sce(sce = sce, groups = unique(colData(sce)$Library), 
                        colData.name = "Library")
sce.single$RA <- sce_RA

corrected <- batch.correction(sce.single)

# Compute tSNE
set.seed(12345)
pca <- prcomp_irlba(t(corrected), n = 50)
tsne <- Rtsne(pca$x, pca = FALSE, perplexity = 200)

# Create new colour vector
new_vector <- c(brewer.pal(n = 8, name = "Set1"), brewer.pal(n = 8, name = "Set2"), brewer.pal(n = 6, name = "Set3"))
names(new_vector) <- unique(colData(sce_RA)$cell_type)
col_vector <- c(metadata(sce)$color_vector, new_vector)

ggplot() +
  geom_point(data = data.frame(tSNE1 = tsne$Y[1:ncol(sce),1],
                  tSNE2 = tsne$Y[1:ncol(sce),2],
                  cluster = colData(sce)$AnnotatedClusters),
             aes(tSNE1, tSNE2, colour = cluster)) + 
    geom_point(data = data.frame(tSNE1 = tsne$Y[(ncol(sce)+1):(ncol(sce)+ncol(sce_RA)),1],
                  tSNE2 = tsne$Y[(ncol(sce)+1):(ncol(sce)+ncol(sce_RA)),2],
                  cell_type = colData(sce_RA)$cell_type),
             aes(tSNE1, tSNE2, colour = cell_type, size = 3)) +
  scale_color_manual(values = col_vector)
```

# RA blocked cells mapped to P15 emptyDrops

```{r P15}
sce.P15 <- sce[,grepl("P15", colData(sce)$Sample)]

# Select only the germ cells
sce.P15 <- sce.P15[,grepl("Pachytene_Spermatocytes|Undifferentiated_Spermatogonia|Differentiating_Spermatogonia", colData(sce.P15)$P15Clusters) | colData(sce.P15)$P15Clusters == "Leptotene/Zygotene"]
sce.P15 <- normalize(sce.P15)

# Select Early germ cells from RA blocked cells
sce_early_RA <- sce_RA[,grepl("A1|ePL|G1|mPL|eP|mP|lPL|Z|L|ln|Spo11KOL1", colData(sce_RA)$cell_type)]
sce_early_RA <- normalize(sce_early_RA)

# Batch correction
corrected <- batch.correction(list(sce.P15, sce_early_RA))

# Visualization
set.seed(1111)
pca <- prcomp_irlba(t(corrected), n = 50)
tsne <- Rtsne(pca$x, pca = FALSE, perplexity = 50)

# Create new colour vector
new_vector <- c(brewer.pal(n = 8, name = "Set1"), brewer.pal(n = 8, name = "Set2"))
names(new_vector) <- unique(colData(sce_early_RA)$cell_type)
col_vector <- c(metadata(sce)$colour_vector.P15, new_vector)

ggplot() +
  geom_point(data = data.frame(tSNE1 = tsne$Y[1:ncol(sce.P15),1],
                  tSNE2 = tsne$Y[1:ncol(sce.P15),2],
                  cluster = colData(sce.P15)$P15Clusters),
             aes(tSNE1, tSNE2, colour = cluster)) + 
    geom_point(data = data.frame(tSNE1 = tsne$Y[(ncol(sce.P15)+1):(ncol(sce.P15)+ncol(sce_early_RA)),1],
                  tSNE2 = tsne$Y[(ncol(sce.P15)+1):(ncol(sce.P15)+ncol(sce_early_RA)),2],
                  cell_type = colData(sce_early_RA)$cell_type),
             aes(tSNE1, tSNE2, colour = cell_type, size = 3)) +
  scale_color_manual(values = col_vector)

# CellRanger filter cluster
# Create new colour vector
new_vector <- c(brewer.pal(n = 8, name = "Set1"), brewer.pal(n = 8, name = "Set2"))
names(new_vector) <- unique(colData(sce_early_RA)$cell_type)
col_vector <- c(metadata(sce)$color_vector, new_vector)

ggplot() +
  geom_point(data = data.frame(tSNE1 = tsne$Y[1:ncol(sce.P15),1],
                  tSNE2 = tsne$Y[1:ncol(sce.P15),2],
                  cluster = colData(sce.P15)$AnnotatedClusters),
             aes(tSNE1, tSNE2, colour = cluster)) + 
    geom_point(data = data.frame(tSNE1 = tsne$Y[(ncol(sce.P15)+1):(ncol(sce.P15)+ncol(sce_early_RA)),1],
                  tSNE2 = tsne$Y[(ncol(sce.P15)+1):(ncol(sce.P15)+ncol(sce_early_RA)),2],
                  cell_type = colData(sce_early_RA)$cell_type),
             aes(tSNE1, tSNE2, colour = cell_type, size = 3)) +
  scale_color_manual(values = col_vector)
```

# RA blocked cells mapped to P15, P20 and P25 cellRanger

```{r P15_P20_P25}
sce <- readRDS("../../../../Dropbox (Cambridge University)/SST_spermatocytes/Analysis/data/10X_data/SCE_all.rds")
sce <- sce[,grepl("B6", colData(sce)$Sample)]
sce <- sce[rownames(sce_RA),]

# Select only the germ cells
sce <- sce[,grepl("Spermatocytes_1|Spermatocytes_2|Spermatocytes_3|Spermatocytes_4|Spermatocytes_5|Spermatocytes_6|Spermatocytes_7|Meiosis|S1|S2|S3|S4|S5|S6|S7|S8|S9|S10|S11|S12|S13|S14", colData(sce)$AnnotatedClusters)]
sce <- normalize(sce)

# Select Early germ cells from RA blocked cells
sce_mid_RA <- sce_RA[,grepl("D|MI|MII|RS1o2|RS3o4|RS5o6|Sox30KORS2o3|RS7o8", colData(sce_RA)$cell_type) | colData(sce_RA)$cell_type == "lP" | colData(sce_RA)$cell_type == "mP"]
sce_mid_RA <- normalize(sce_mid_RA)

# Batch correction
sce.single <- split.sce(sce = sce, groups = unique(colData(sce)$Library), 
                        colData.name = "Library")
sce.single$RA <- sce_mid_RA

corrected <- batch.correction(sce.single)

# Visualization
set.seed(1111)
pca <- prcomp_irlba(t(corrected), n = 50)
tsne <- Rtsne(pca$x, pca = FALSE, perplexity = 50)

# Create new colour vector
new_vector <- c(brewer.pal(n = 8, name = "Set1"), brewer.pal(n = 8, name = "Set2"))
names(new_vector) <- unique(colData(sce_mid_RA)$cell_type)
col_vector <- c(metadata(sce)$color_vector, new_vector)

ggplot() +
  geom_point(data = data.frame(tSNE1 = tsne$Y[1:ncol(sce),1],
                  tSNE2 = tsne$Y[1:ncol(sce),2],
                  cluster = colData(sce)$AnnotatedClusters),
             aes(tSNE1, tSNE2, colour = cluster)) + 
    geom_point(data = data.frame(tSNE1 = tsne$Y[(ncol(sce)+1):(ncol(sce)+ncol(sce_mid_RA)),1],
                  tSNE2 = tsne$Y[(ncol(sce)+1):(ncol(sce)+ncol(sce_mid_RA)),2],
                  cell_type = colData(sce_mid_RA)$cell_type),
             aes(tSNE1, tSNE2, colour = cell_type, size = 3)) +
  scale_color_manual(values = col_vector)
```